### ISSUE TITLE
Support Flux bnb-nf4

### ISSUE THREAD

**Issue by Nina9194** [mcmonkeyprojects/SwarmUI#156]
### Feature Idea

Please integrate this:
https://github.com/comfyanonymous/ComfyUI_bitsandbytes_NF4

**Comment by mcmonkey4eva** [comment]
Yep, added

It will autodetect that they're NF4, then the first time you try to run any NF4 model, it will give you a popup like this asking permission to install the (AGPL Licensed) extension to run them.

![image-17](https://github.com/user-attachments/assets/d79fde2a-34cb-4377-b4da-1ab30d7fb255)

*Note if you already have NF4 models saved, you'll want to go to Utilities -> Reset All Metadata to make it load

After that autoinstall completes, these models will Just Work(TM) like any other, with around half the VRAM cost!

**Comment by RamonGuthrie** [comment]
Do Flux Loras work when using this, because in ComfyUI they don't it is an issue only with Flux nf4 model

**Comment by mcmonkey4eva** [comment]
Nope. It uses the comfy ext on the inside, so loras won't work atm

**Comment by clb92** [comment]
Does not work for me.

Here's what I did:

1. Update & restart SwarmUI
2. Reset All Metadata because I already had the bnb-nf4 model in my folder
3. Restart SwarmUI again
4. Select model and click Generate
5. Click Install on the popup, and wait for it to install the nf4 support
6. Try clicking Generate again (I've tried restarting once more too, no difference)

The error I get is from the self-starting ComfyUI backend:

```
2024-08-12 12:29:13.313 [ComfyUI-0] [STDERR] got prompt
2024-08-12 12:29:13.318 [ComfyUI-0] [STDERR] !!! Exception during processing!!! load_checkpoint_guess_config() got an unexpected keyword argument 'model_options'
2024-08-12 12:29:13.319 [ComfyUI-0] [STDERR] Traceback (most recent call last):
2024-08-12 12:29:13.320 [ComfyUI-0] [STDERR]   File "E:\STABLEDIFFUSION\swarmui\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 152, in recursive_execute
2024-08-12 12:29:13.321 [ComfyUI-0] [STDERR]     output_data, output_ui = get_output_data(obj, input_data_all)
2024-08-12 12:29:13.323 [ComfyUI-0] [STDERR]                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-12 12:29:13.324 [ComfyUI-0] [STDERR]   File "E:\STABLEDIFFUSION\swarmui\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 82, in get_output_data
2024-08-12 12:29:13.325 [ComfyUI-0] [STDERR]     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
2024-08-12 12:29:13.326 [ComfyUI-0] [STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-12 12:29:13.326 [ComfyUI-0] [STDERR]   File "E:\STABLEDIFFUSION\swarmui\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 75, in map_node_over_list
2024-08-12 12:29:13.327 [ComfyUI-0] [STDERR]     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
2024-08-12 12:29:13.328 [ComfyUI-0] [STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-12 12:29:13.329 [ComfyUI-0] [STDERR]   File "E:\STABLEDIFFUSION\swarmui\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes\ComfyUI_bitsandbytes_NF4\__init__.py", line 178, in load_checkpoint
2024-08-12 12:29:13.329 [ComfyUI-0] [STDERR]     out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"), model_options={"custom_operations": OPS})
2024-08-12 12:29:13.330 [ComfyUI-0] [STDERR]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-12 12:29:13.333 [ComfyUI-0] [STDERR] TypeError: load_checkpoint_guess_config() got an unexpected keyword argument 'model_options'
2024-08-12 12:29:13.334 [ComfyUI-0] [STDERR] 
2024-08-12 12:29:13.334 [ComfyUI-0] [STDERR] Prompt executed in 0.01 seconds
```

**Comment by mcmonkey4eva** [comment]
Your ComfyUI is outdated, make sure in Server->Backends that auto update is enabled on the comfy backend

**Comment by clb92** [comment]
AutoUpdate is set to "Always update" on the backend.

**Comment by clb92** [comment]
I had to manually find and run the update script for the comfyui backend to get it to update. For some reason it just didn't happen through SwarmUI.
