### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorrt'

### ISSUE THREAD

**Issue by ScorpScorp** [mcmonkeyprojects/SwarmUI#173]
### Your question

Repeatedly get this error on startup, would appreciate any assistance possible in resolving.

### Logs

```powershell
12:35:59.278 [Init] Self-Start ComfyUI-0 on port 7822 is loading...
12:36:05.173 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
12:36:05.175 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 1982, in load_custom_node
12:36:05.176 [Warning] [ComfyUI-0/STDERR]     module_spec.loader.exec_module(module)
12:36:05.177 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
12:36:05.179 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
12:36:05.183 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes\ComfyUI_TensorRT\__init__.py", line 1, in <module>
12:36:05.184 [Warning] [ComfyUI-0/STDERR]     from .tensorrt_convert import DYNAMIC_TRT_MODEL_CONVERSION
12:36:05.187 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes\ComfyUI_TensorRT\tensorrt_convert.py", line 7, in <module>
12:36:05.189 [Warning] [ComfyUI-0/STDERR]     import tensorrt as trt
12:36:05.190 [Warning] [ComfyUI-0/STDERR] ModuleNotFoundError: No module named 'tensorrt'
12:36:05.191 [Warning] [ComfyUI-0/STDERR]
```

### Other

I'm up-to-date, and strangely enough was not receiving this error when I first installed SwarmUI.

**Comment by mcmonkey4eva** [comment]
Make sure your SwarmUI is version 0.9.x -- if it's 0.6.x you're on the legacy Stable repo and need to migrate to the modern one.

---

TensorRT is notoriously unreliable at installing properly, laziest approach is you can delete `C:\Users\User\Documents\StableDiffusion\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes\ComfyUI_TensorRT` and then restart Swarm and try again.

Alternately, open `C:\Users\User\Documents\StableDiffusion\StableSwarmUI\src\dlbackend\comfy` in a terminal and run command `python_embeded\python.exe -s -m pip install tensorrt`
