### ISSUE TITLE
Support loading a specific type of GGUF

### ISSUE THREAD

**Issue by Taruvi** [mcmonkeyprojects/SwarmUI#185]
### Feature Idea

I'd like to load [this file](https://civitai.com/models/657607/gguf-fastflux-flux1-schnell-merged-with-flux1-dev) to test it.

I get a popup error saying:
```
All available backends failed to load the model.
```
Debug Logs:

When the model is in the normal Models directory:
```
2024-08-20 12:10:40.450 [Info] User local requested 1 image with model 'flux/GGUF- FastFlux -Flux-1-Schnell Merged with Flux-1-Dev- - Q4_0_v2.safetensors'...
2024-08-20 12:10:40.451 [Debug] [BackendHandler] Backend request #5 for model flux/GGUF- FastFlux -Flux-1-Schnell Merged with Flux-1-Dev- - Q4_0_v2.safetensors, maxWait=7.00:00:00.
2024-08-20 12:10:40.451 [Debug] [BackendHandler] backend #0 will load a model: flux/GGUF- FastFlux -Flux-1-Schnell Merged with Flux-1-Dev- - Q4_0_v2.safetensors, with 1 requests waiting for 0 seconds
2024-08-20 12:10:40.484 [Debug] [ComfyUI-0/STDERR] got prompt
2024-08-20 12:10:40.502 [Debug] [ComfyUI-0/STDERR] !!! Exception during processing !!! Error while deserializing header: HeaderTooLarge
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/execution.py", line 316, in execute
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/execution.py", line 191, in get_output_data
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/execution.py", line 168, in _map_node_over_list
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/execution.py", line 157, in process_inputs
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/nodes.py", line 539, in load_checkpoint
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]     out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/comfy/sd.py", line 518, in load_checkpoint_guess_config
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]     sd = comfy.utils.load_torch_file(ckpt_path)
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/comfy/utils.py", line 34, in load_torch_file
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]     sd = safetensors.torch.load_file(ckpt, device=device.type)
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/venv/lib/python3.11/site-packages/safetensors/torch.py", line 311, in load_file
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]     with safe_open(filename, framework="pt", device=device) as f:
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR] safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
2024-08-20 12:10:40.504 [Warning] [ComfyUI-0/STDERR] 
2024-08-20 12:10:40.506 [Debug] [ComfyUI-0/STDERR] Prompt executed in 0.01 seconds
2024-08-20 12:10:40.645 [Error] [BackendHandler] backend #0 failed to load model with error: ComfyUI execution error: Error while deserializing header: HeaderTooLarge
2024-08-20 12:10:40.645 [Warning] [BackendHandler] backend #0 failed to load model flux/GGUF- FastFlux -Flux-1-Schnell Merged with Flux-1-Dev- - Q4_0_v2.safetensors
2024-08-20 12:10:40.645 [Debug] Will deny backends: 0
2024-08-20 12:10:41.451 [Warning] [BackendHandler] All backends failed to load the model! Cannot generate anything.
2024-08-20 12:10:41.451 [Error] [BackendHandler] Backend request #5 failed: All available backends failed to load the model.
2024-08-20 12:10:41.451 [Error] [BackendHandler] Backend request #5 failed: All available backends failed to load the model.
2024-08-20 12:10:41.451 [Debug] [BackendHandler] Backend request #5 finished.
2024-08-20 12:10:41.451 [Debug] Refused to generate image for local: All available backends failed to load the model.
```
I moved it to the ```unet``` directory since it doesn't include the clip or vae and got this:
```
2024-08-20 12:15:38.677 [Debug] [Load ComfyUI Self-Starting #0] Got valid value set, will parse...
2024-08-20 12:15:38.677 [Debug] Comfy backend 0 using model folder format: forward slash / as no backslash was found
2024-08-20 12:15:38.678 [Debug] [Load ComfyUI Self-Starting #0] Done parsing value set.
2024-08-20 12:15:38.716 [Warning] Failed to load metadata for flux/GGUF- FastFlux -Flux-1-Schnell Merged with Flux-1-Dev- - Q4_0_v2.safetensors:
SwarmUI.Utils.SwarmReadableErrorException: Improper safetensors file /config/07-SwarmUI/SwarmUI/Models/unet/flux/GGUF- FastFlux -Flux-1-Schnell Merged with Flux-1-Dev- - Q4_0_v2.safetensors. Wrong file type, or unreasonable header length: 193340853072
   at SwarmUI.Text2Image.T2IModel.GetSafetensorsHeaderFrom(String modelPath) in /config/07-SwarmUI/SwarmUI/src/Text2Image/T2IModel.cs:line 103
   at SwarmUI.Text2Image.T2IModelHandler.LoadMetadata(T2IModel model) in /config/07-SwarmUI/SwarmUI/src/Text2Image/T2IModelHandler.cs:line 462
   at SwarmUI.Text2Image.T2IModelHandler.<>c__DisplayClass26_0.<AddAllFromFolder>b__1(String file) in /config/07-SwarmUI/SwarmUI/src/Text2Image/T2IModelHandler.cs:line 710
2024-08-20 12:15:39.183 [Debug] Data refreshed!
2024-08-20 12:16:04.444 [Debug] [Load ComfyUI Self-Starting #0] Got valid value set, will parse...
2024-08-20 12:16:04.444 [Debug] Comfy backend 0 using model folder format: forward slash / as no backslash was found
2024-08-20 12:16:04.444 [Debug] [Load ComfyUI Self-Starting #0] Done parsing value set.
2024-08-20 12:16:04.946 [Debug] Data refreshed!
2024-08-20 12:17:08.309 [Info] User local requested 1 image with model 'flux/GGUF- FastFlux -Flux-1-Schnell Merged with Flux-1-Dev- - Q4_0_v2.safetensors'...
2024-08-20 12:17:08.309 [Debug] [BackendHandler] Backend request #7 for model flux/GGUF- FastFlux -Flux-1-Schnell Merged with Flux-1-Dev- - Q4_0_v2.safetensors, maxWait=7.00:00:00.
2024-08-20 12:17:08.309 [Debug] [BackendHandler] backend #0 will load a model: flux/GGUF- FastFlux -Flux-1-Schnell Merged with Flux-1-Dev- - Q4_0_v2.safetensors, with 1 requests waiting for 0 seconds
2024-08-20 12:17:08.495 [Debug] [ComfyUI-0/STDERR] got prompt
2024-08-20 12:17:08.534 [Debug] [ComfyUI-0/STDERR] !!! Exception during processing !!! Error while deserializing header: HeaderTooLarge
2024-08-20 12:17:08.536 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
2024-08-20 12:17:08.536 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/execution.py", line 316, in execute
2024-08-20 12:17:08.536 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-08-20 12:17:08.536 [Warning] [ComfyUI-0/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 12:17:08.536 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/execution.py", line 191, in get_output_data
2024-08-20 12:17:08.536 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-08-20 12:17:08.536 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/execution.py", line 168, in _map_node_over_list
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/execution.py", line 157, in process_inputs
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/nodes.py", line 874, in load_unet
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]     model = comfy.sd.load_diffusion_model(unet_path, model_options=model_options)
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/comfy/sd.py", line 655, in load_diffusion_model
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]     sd = comfy.utils.load_torch_file(unet_path)
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/comfy/utils.py", line 34, in load_torch_file
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]     sd = safetensors.torch.load_file(ckpt, device=device.type)
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]   File "/config/07-SwarmUI/SwarmUI/dlbackend/ComfyUI/venv/lib/python3.11/site-packages/safetensors/torch.py", line 311, in load_file
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]     with safe_open(filename, framework="pt", device=device) as f:
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR] safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
2024-08-20 12:17:08.537 [Warning] [ComfyUI-0/STDERR] 
2024-08-20 12:17:08.538 [Debug] [ComfyUI-0/STDERR] Prompt executed in 0.01 seconds
2024-08-20 12:17:08.678 [Error] [BackendHandler] backend #0 failed to load model with error: ComfyUI execution error: Error while deserializing header: HeaderTooLarge
2024-08-20 12:17:08.679 [Warning] [BackendHandler] backend #0 failed to load model flux/GGUF- FastFlux -Flux-1-Schnell Merged with Flux-1-Dev- - Q4_0_v2.safetensors
2024-08-20 12:17:08.679 [Debug] Will deny backends: 0
2024-08-20 12:17:09.309 [Warning] [BackendHandler] All backends failed to load the model! Cannot generate anything.
2024-08-20 12:17:09.309 [Error] [BackendHandler] Backend request #7 failed: All available backends failed to load the model.
2024-08-20 12:17:09.309 [Error] [BackendHandler] Backend request #7 failed: All available backends failed to load the model.
2024-08-20 12:17:09.309 [Debug] [BackendHandler] Backend request #7 finished.
2024-08-20 12:17:09.309 [Debug] Refused to generate image for local: All available backends failed to load the model.
```
Just to make sure I wasn't missing any crucial updates, I restarted my Docker container which automatically updates Swarm and all the associated Comfy stuff minutes before I've posted this. So it's all up to date.

**Comment by mcmonkey4eva** [comment]
Your file is supposedly a gguf file, but you have it saved with `.safetensors` extension -- this is invalid, gguf files need a `gguf` file extension

**Comment by mcmonkey4eva** [comment]
oh, model downloader is currently entirely incapable here atm - in addition to being gguf, the downloader also doesn't have a way to understand that some files (including all currently released gguf models) belong in `unets` instead of normal folders.

... probably need at least error handling / refusal for gguf files

**Comment by mcmonkey4eva** [comment]
swapped to just refuse for now
