### ISSUE TITLE
Simple Tab Questions

### ISSUE THREAD

**Issue by dapa5900** [mcmonkeyprojects/SwarmUI#186]
### Your question

Hi,

is there a documentation about creating workflows for the simple tab? I've had look in the example workflow and also managed to utilize some other SwarmInput nodes however I also ran into some issues/questions:

1. Is it possible to bypass parts of the workflow if you don't want to use them. For example, skip controlnet usage (Basically "Use controlnet On/Off")?
2. When using a SwarmInputImage, you can not define a default image. In my case this requires the user to always upload a picture manually, even if they don't need it (for example, if you’d like to skip the controlnet part as described in 1. you'd still need to upload a picture and then set the controlnet strength to 0). If you don't upload a picture the workflow execution doesn't work and you just get the log error below via console.  Here it would be also helpful to give the user some more precise error indication in the GUI about that apart from just the rotating loading animation. 
3. Is it possible to pause the generation somehow, for example when you're creating a batch of 4 images for the base image generation but want to only select one of them for further workflow processing (eg. highres fix, further image processing etc.)

Thank you!

### Logs

```powershell
13:30:22.368 [Error] Error in websocket handler: System.AggregateException: One or more errors occurred. (Invalid value for parameter StructureRef Image)
 ---> System.Exception: Invalid value for parameter StructureRef Image
 ---> System.ArgumentException: Data is empty! (Parameter 'data')
   at SwarmUI.Utils.Image..ctor(Byte[] data, ImageType type, String extension) in C:\StableDiffusion\STABILITYMATRIX\Data\Packages\SwarmUI\src\Utils\Image.cs:line 74
   at SwarmUI.Text2Image.T2IParamInput.Set(T2IParamType param, String val) in C:\StableDiffusion\STABILITYMATRIX\Data\Packages\SwarmUI\src\Text2Image\T2IParamInput.cs:line 896
   at SwarmUI.Text2Image.T2IParamTypes.ApplyParameter(String paramTypeName, String value, T2IParamInput data) in C:\StableDiffusion\STABILITYMATRIX\Data\Packages\SwarmUI\src\Text2Image\T2IParamTypes.cs:line 857
   --- End of inner exception stack trace ---
   at SwarmUI.Text2Image.T2IParamTypes.ApplyParameter(String paramTypeName, String value, T2IParamInput data) in C:\StableDiffusion\STABILITYMATRIX\Data\Packages\SwarmUI\src\Text2Image\T2IParamTypes.cs:line 865
   at SwarmUI.WebAPI.T2IAPI.RequestToParams(Session session, JObject rawInput) in C:\StableDiffusion\STABILITYMATRIX\Data\Packages\SwarmUI\src\WebAPI\T2IAPI.cs:line 147
   at SwarmUI.WebAPI.T2IAPI.GenT2I_Internal(Session session, ValueTuple`2 input, Action`1 output, Boolean isWS) in C:\StableDiffusion\STABILITYMATRIX\Data\Packages\SwarmUI\src\WebAPI\T2IAPI.cs:line 187
   --- End of inner exception stack trace ---
```

**Comment by mcmonkey4eva** [comment]
Most of that's all waiting on some in-progress upstream ComfyUI core upgrades.
We just got _Execution Inversion_ merged in, the first fundamental step towards being able to have a single comfy workflow branch between different paths as-needed, or loop dynamically, or etc.

For now, understand the Simple tab to be effectively limited to, as the name suggests, Simple usages of workflows. More advanced features to come in time as Comfy itself gets more core upgrades to be able to support more advanced usages directly.

The capacity of eg Swarm's generate tab to turn features like controlnet on/off comes from the fact that it, as the name suggests, _Generates_ workflows on the fly based on what you've selected.

**Comment by dapa5900** [comment]
Great, thanks for the clarification.
