### ISSUE TITLE
Error: [Swarm] RemBg not available

### ISSUE THREAD

**Issue by mbac** [mcmonkeyprojects/SwarmUI#220]
### Your question

Hi,

I've been trying multiple reinstalls of SwarmUI on vast.ai machines, and I keep getting this warning:

```
20:47:40.495 [Init] Self-Start ComfyUI-0 on port 7821 started.
20:47:40.496 [Init] Initializing backend #0 - ComfyUI Self-Starting...
20:47:41.030 [Init] Self-Start ComfyUI-0 on port 7822 is loading...
20:47:44.651 [Warning] [ComfyUI-0/STDOUT] Error: [Swarm] RemBg not available
20:47:44.651 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
20:47:44.652 [Warning] [ComfyUI-0/STDERR]   File "/root/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyExtra/__init__.py", line 7, in <module>
```
I have seen a similar issue here but to be honest, I don't understand how it was solved. I've tried starting the ComfyUI installation manually, and it works. Also, the installs for rembg and other Python packages exit without issue during the SwarmUI installation process; if I enter Comfy's venv the packages seem to be installed ("Requirements already satisfied…")

Full log entry below.

### Logs

https://paste.denizenscript.com/View/126097

**Comment by mcmonkey4eva** [comment]
Your main error in that log is `ImportError: libGL.so.1: cannot open shared object file: No such file or directory`

Which this stackoverflow post suggests a fix for: https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo

btw please do not run user software as root

**Comment by mbac** [comment]
Thanks for your input, really. I'm really no IT expert, but I thought as much about running as root; however, it seems the standard with cloud GPU Docker images, so I really wouldn't know how to do differently. I've yet to find an image that starts you in a normal user, and it's really too much work to systematically customize images for all the apps I use, at least for me.

**Comment by mcmonkey4eva** [comment]
Oh, for docker, use Swarm's docker scripts in the repo's root (there's a docker-compose and a sh script to your preference). The libgl error was fixed for that a few months ago https://github.com/Stability-AI/StableSwarmUI/pull/331

**Comment by mbac** [comment]
Hi!

I'm running into the same error when installing on a Vast.ai image. The machine instance is of course loading a Docker image, but I'm installing Swarm with my own shell script using git and dotnet as in Dr. Furkan's (SECourses) scripts. The image is the following:

[pytorch/pytorch:2.4.0-cuda12.4-cudnn9-runtime](https://hub.docker.com/layers/pytorch/pytorch/2.4.0-cuda12.4-cudnn9-runtime/images/sha256-393fa73fbcfd290b46483cebc29a284fcc10d5be493e3d4844f9781152c2daa4?context=explore)

Comfy is using Python 3.11 in its venv:

```
20:25:13.609 [Warning] [ComfyUI-0/STDOUT] Error: [Swarm] RemBg not available
20:25:13.609 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
20:25:13.610 [Warning] [ComfyUI-0/STDERR]   File "/workspace/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyExtra/__init__.py", line 7, in <module>
20:25:13.610 [Warning] [ComfyUI-0/STDERR]     from . import SwarmRemBg
20:25:13.610 [Warning] [ComfyUI-0/STDERR]   File "/workspace/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyExtra/SwarmRemBg.py", line 4, in <module>
20:25:13.610 [Warning] [ComfyUI-0/STDERR]     from rembg import remove
20:25:13.611 [Warning] [ComfyUI-0/STDERR]   File "/workspace/SwarmUI/dlbackend/ComfyUI/venv/lib/python3.11/site-packages/rembg/__init__.py", line 5, in <module>
20:25:13.611 [Warning] [ComfyUI-0/STDERR]     from .bg import remove
20:25:13.611 [Warning] [ComfyUI-0/STDERR]   File "/workspace/SwarmUI/dlbackend/ComfyUI/venv/lib/python3.11/site-packages/rembg/bg.py", line 7, in <module>
20:25:13.611 [Warning] [ComfyUI-0/STDERR]     from cv2 import (
20:25:13.611 [Warning] [ComfyUI-0/STDERR]   File "/workspace/SwarmUI/dlbackend/ComfyUI/venv/lib/python3.11/site-packages/cv2/__init__.py", line 181, in <module>
20:25:13.612 [Warning] [ComfyUI-0/STDERR]     bootstrap()
20:25:13.612 [Warning] [ComfyUI-0/STDERR]   File "/workspace/SwarmUI/dlbackend/ComfyUI/venv/lib/python3.11/site-packages/cv2/__init__.py", line 153, in bootstrap
20:25:13.612 [Warning] [ComfyUI-0/STDERR]     native_module = importlib.import_module("cv2")
20:25:13.612 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20:25:13.612 [Warning] [ComfyUI-0/STDERR]   File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
20:25:13.613 [Warning] [ComfyUI-0/STDERR]     return _bootstrap._gcd_import(name[level:], package, level)
20:25:13.613 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20:25:13.613 [Warning] [ComfyUI-0/STDERR] ImportError: libGL.so.1: cannot open shared object file: No such file or directory
20:25:13.616 [Warning] [ComfyUI-0/STDERR] 
```

**Comment by mcmonkey4eva** [comment]
Then you need to copy the docker commands https://github.com/mcmonkeyprojects/SwarmUI/blob/master/Dockerfile
note the 'apt install' commands specifically
