### ISSUE TITLE
Backend does not have that model.

### ISSUE THREAD

**Issue by ZeroCool22** [mcmonkeyprojects/SwarmUI#225]
### Expected Behavior

Don't have that error....

### Actual Behavior

 
![Screenshot_7](https://github.com/user-attachments/assets/02403f45-655d-4d46-a227-42ad90964404)

![Screenshot_5](https://github.com/user-attachments/assets/8da3860d-f9a6-45da-a6e0-8cdcbfb20b27)

![Screenshot_6](https://github.com/user-attachments/assets/09246acc-a5c3-461c-ace1-51a78450c553)

### Steps to Reproduce

Generate.

### Debug Logs

```
2024-08-30 01:46:31.934 [Init] === SwarmUI v0.9.2.2 Starting at 2024-08-30 01:46:31 ===
2024-08-30 01:46:31.993 [Init] Prepping extension: SwarmUI.Builtin_ScorersExtension.ScorersExtension...
2024-08-30 01:46:32.000 [Init] Prepping extension: SwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
2024-08-30 01:46:32.001 [Init] Prepping extension: SwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
2024-08-30 01:46:32.001 [Init] Prepping extension: SwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
2024-08-30 01:46:32.002 [Init] Prepping extension: SwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
2024-08-30 01:46:32.002 [Init] Prepping extension: SwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
2024-08-30 01:46:32.046 [Init] Parsing command line...
2024-08-30 01:46:32.047 [Init] Loading settings file...
2024-08-30 01:46:32.066 [Init] Re-saving settings file...
2024-08-30 01:46:32.081 [Init] Applying command line settings...
2024-08-30 01:46:32.113 [Init] Prepping options...
2024-08-30 01:46:32.181 [Error] Failed to get git commit date: System.FormatException: The string 'fatal: detected dubious ownership in repository at 'C:/Users/ZeroCool22/Desktop/SwarmUI'
'C:/Users/ZeroCool22/Desktop/SwarmUI/.git' is owned by:
	'S-1-5-32-544'
but the current user is:
	'S-1-5-21-353915190-2478586258-3895337694-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory C:/Users/ZeroCool22/Desktop/SwarmUI' was not recognized as a valid DateTime. There is an unknown word starting at index '0'.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
   at System.DateTimeOffset.Parse(String input)
   at SwarmUI.Core.Program.<>c.<<Main>b__22_4>d.MoveNext() in C:\Users\ZeroCool22\Desktop\SwarmUI\src\Core\Program.cs:line 165
2024-08-30 01:46:32.233 [Error] Internal error in async task: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SwarmUI.Core.Program.<>c.<<Main>b__22_3>d.MoveNext()
--- End of stack trace from previous location ---
   at SwarmUI.Utils.Utilities.<>c__DisplayClass42_0.<<RunCheckedTask>b__0>d.MoveNext() in C:\Users\ZeroCool22\Desktop\SwarmUI\src\Utils\Utilities.cs:line 474
2024-08-30 01:46:32.253 [Init] Loading models list...
2024-08-30 01:46:32.261 [Init] CPU Cores: 24 | RAM: 31.91 GiB total, 23.62 GiB available
2024-08-30 01:46:32.261 [Init] GPU 0: NVIDIA GeForce RTX 4070 Ti SUPER | Temp 28C | Util 3% GPU, 0% Memory | VRAM 15.99 GiB total, 15.34 GiB free, 358.00 MiB used
2024-08-30 01:46:32.289 [Init] Loading backends...
2024-08-30 01:46:32.290 [Init] Loading backends from file...
2024-08-30 01:46:32.292 [Init] Prepping API...
2024-08-30 01:46:32.293 [Init] Initializing backend #0 - ComfyUI Self-Starting...
2024-08-30 01:46:32.294 [Init] Prepping webserver...
2024-08-30 01:46:32.296 [Init] Backend request handler loop ready...
2024-08-30 01:46:32.513 [Init] Scan for web extensions...
2024-08-30 01:46:32.515 [Init] Readying extensions for launch...
2024-08-30 01:46:32.515 [Init] Launching server...
2024-08-30 01:46:32.516 [Init] Starting webserver on http://localhost:7801
2024-08-30 01:46:32.566 [Init] Program is running.
2024-08-30 01:46:33.066 [Init] Launch web browser...
2024-08-30 01:46:33.281 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
2024-08-30 01:46:34.154 [Info] Creating new admin session 'local' for ::1
2024-08-30 01:46:38.440 [Init] Self-Start ComfyUI-0 on port 7821 started.
2024-08-30 01:46:41.601 [Info] User local requested 1 image with model 'flux1-dev-Q8_0.gguf'...
2024-08-30 01:46:41.607 [Warning] [BackendHandler] No backends match the request! Cannot generate anything. Backends refused for the following reason(s):
- Request requires model 'flux1-dev-Q8_0.gguf' but the backend does not have that model
2024-08-30 01:46:41.608 [Error] [BackendHandler] Backend request #1 failed: No backends match the settings of the request given! Backends refused for the following reason(s):
- Request requires model 'flux1-dev-Q8_0.gguf' but the backend does not have that model
2024-08-30 01:51:54.955 [Info] Creating new admin session 'local' for ::1
```

**Comment by mcmonkey4eva** [comment]
that's a backbone-only model, it needs to be in `(YourModelRoot)/diffusion_models` (folder previously named `unet`)

Also note the git warning in your log, you have something wonked with windows account ownership

**Comment by ZeroCool22** [comment]
> that's a backbone-only model, it needs to be in `(YourModelRoot)/diffusion_models` (folder previously named `unet`)
> 
> Also note the git warning in your log, you have something wonked with windows account ownership


```
02:07:20.070 [Info] User local requested 1 image with model 'flux1-dev-Q8_0.gguf'...
02:07:22.155 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
02:07:22.156 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 317, in execute
02:07:22.156 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
02:07:22.156 [Warning] [ComfyUI-0/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02:07:22.157 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 192, in get_output_data
02:07:22.157 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
02:07:22.157 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02:07:22.158 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 169, in _map_node_over_list
02:07:22.158 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
02:07:22.158 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 158, in process_inputs
02:07:22.159 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
02:07:22.159 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02:07:22.159 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 539, in load_checkpoint
02:07:22.160 [Warning] [ComfyUI-0/STDERR]     out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
02:07:22.160 [Warning] [ComfyUI-0/STDERR]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02:07:22.160 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\ComfyUI\comfy\sd.py", line 524, in load_checkpoint_guess_config
02:07:22.161 [Warning] [ComfyUI-0/STDERR]     sd = comfy.utils.load_torch_file(ckpt_path)
02:07:22.161 [Warning] [ComfyUI-0/STDERR]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02:07:22.161 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\ComfyUI\comfy\utils.py", line 43, in load_torch_file
02:07:22.162 [Warning] [ComfyUI-0/STDERR]     pl_sd = torch.load(ckpt, map_location=device, pickle_module=comfy.checkpoint_pickle)
02:07:22.162 [Warning] [ComfyUI-0/STDERR]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02:07:22.162 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\serialization.py", line 1040, in load
02:07:22.163 [Warning] [ComfyUI-0/STDERR]     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
02:07:22.163 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02:07:22.164 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\serialization.py", line 1262, in _legacy_load
02:07:22.164 [Warning] [ComfyUI-0/STDERR]     magic_number = pickle_module.load(f, **pickle_load_args)
02:07:22.164 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02:07:22.164 [Warning] [ComfyUI-0/STDERR] _pickle.UnpicklingError: invalid load key, '\x03'.
02:07:22.165 [Warning] [ComfyUI-0/STDERR]
02:07:22.238 [Error] [BackendHandler] backend #0 failed to load model with error: ComfyUI execution error: invalid load key, '\x03'.
02:07:22.239 [Warning] [BackendHandler] backend #0 failed to load model flux1-dev-Q8_0.gguf
02:07:23.106 [Warning] [BackendHandler] All backends failed to load the model! Cannot generate anything.
02:07:23.106 [Error] [BackendHandler] Backend request #1 failed: All available backends failed to load the model.
02:07:23.107 [Error] [BackendHandler] Backend request #1 failed: All available backends failed to load the model.
```

**Comment by ZeroCool22** [comment]
![Screenshot_8](https://github.com/user-attachments/assets/040da2d6-db15-47bc-8023-bd9e6c1357c0)

**Comment by ZeroCool22** [comment]
I did what you suggested here: https://github.com/mcmonkeyprojects/SwarmUI/issues/212

![Screenshot_9](https://github.com/user-attachments/assets/9fb010dd-8bd4-4354-be14-171a28f9bf7c)

But still same error.

```
2024-08-30 02:35:50.240 [Init] === SwarmUI v0.9.2.2 Starting at 2024-08-30 02:35:50 ===
2024-08-30 02:35:50.287 [Init] Prepping extension: SwarmUI.Builtin_ScorersExtension.ScorersExtension...
2024-08-30 02:35:50.295 [Init] Prepping extension: SwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
2024-08-30 02:35:50.295 [Init] Prepping extension: SwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
2024-08-30 02:35:50.296 [Init] Prepping extension: SwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
2024-08-30 02:35:50.296 [Init] Prepping extension: SwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
2024-08-30 02:35:50.297 [Init] Prepping extension: SwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
2024-08-30 02:35:50.344 [Init] Parsing command line...
2024-08-30 02:35:50.345 [Init] Loading settings file...
2024-08-30 02:35:50.364 [Init] Re-saving settings file...
2024-08-30 02:35:50.380 [Init] Applying command line settings...
2024-08-30 02:35:50.411 [Init] Prepping options...
2024-08-30 02:35:50.556 [Init] Loading models list...
2024-08-30 02:35:50.578 [Init] CPU Cores: 24 | RAM: 31.91 GiB total, 24.63 GiB available
2024-08-30 02:35:50.578 [Init] GPU 0: NVIDIA GeForce RTX 4070 Ti SUPER | Temp 29C | Util 1% GPU, 0% Memory | VRAM 15.99 GiB total, 15.36 GiB free, 332.00 MiB used
2024-08-30 02:35:50.598 [Init] Loading backends...
2024-08-30 02:35:50.599 [Init] Loading backends from file...
2024-08-30 02:35:50.601 [Init] Prepping API...
2024-08-30 02:35:50.601 [Init] Initializing backend #0 - ComfyUI Self-Starting...
2024-08-30 02:35:50.603 [Init] Prepping webserver...
2024-08-30 02:35:50.605 [Init] Backend request handler loop ready...
2024-08-30 02:35:50.846 [Init] Scan for web extensions...
2024-08-30 02:35:50.850 [Init] Readying extensions for launch...
2024-08-30 02:35:50.851 [Init] Launching server...
2024-08-30 02:35:50.851 [Init] Starting webserver on http://localhost:7801
2024-08-30 02:35:51.307 [Init] Current git commit marked as date 2024-08-30 00:54:24
2024-08-30 02:35:51.346 [Init] Swarm is up to date! You have version 0.9.2.2, and 0.9.2-Beta is the latest.
2024-08-30 02:35:51.346 [Init] Program is running.
2024-08-30 02:35:51.662 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
2024-08-30 02:35:51.860 [Init] Launch web browser...
2024-08-30 02:35:53.657 [Info] Creating new admin session 'local' for 127.0.0.1
2024-08-30 02:36:00.373 [Init] Self-Start ComfyUI-0 on port 7821 started.
2024-08-30 02:36:25.879 [Info] User local requested 1 image with model 'flux1-dev-Q8_0.gguf'...
2024-08-30 02:36:27.952 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
2024-08-30 02:36:27.953 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 317, in execute
2024-08-30 02:36:27.953 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-08-30 02:36:27.953 [Warning] [ComfyUI-0/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-30 02:36:27.953 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 192, in get_output_data
2024-08-30 02:36:27.954 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-08-30 02:36:27.954 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-30 02:36:27.954 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 169, in _map_node_over_list
2024-08-30 02:36:27.954 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
2024-08-30 02:36:27.955 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 158, in process_inputs
2024-08-30 02:36:27.955 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
2024-08-30 02:36:27.955 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-30 02:36:27.955 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 539, in load_checkpoint
2024-08-30 02:36:27.955 [Warning] [ComfyUI-0/STDERR]     out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
2024-08-30 02:36:27.956 [Warning] [ComfyUI-0/STDERR]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-30 02:36:27.956 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\ComfyUI\comfy\sd.py", line 524, in load_checkpoint_guess_config
2024-08-30 02:36:27.956 [Warning] [ComfyUI-0/STDERR]     sd = comfy.utils.load_torch_file(ckpt_path)
2024-08-30 02:36:27.956 [Warning] [ComfyUI-0/STDERR]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-30 02:36:27.957 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\ComfyUI\comfy\utils.py", line 43, in load_torch_file
2024-08-30 02:36:27.957 [Warning] [ComfyUI-0/STDERR]     pl_sd = torch.load(ckpt, map_location=device, pickle_module=comfy.checkpoint_pickle)
2024-08-30 02:36:27.957 [Warning] [ComfyUI-0/STDERR]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-30 02:36:27.957 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\serialization.py", line 1040, in load
2024-08-30 02:36:27.958 [Warning] [ComfyUI-0/STDERR]     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
2024-08-30 02:36:27.958 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-30 02:36:27.958 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\ZeroCool22\Desktop\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\serialization.py", line 1262, in _legacy_load
2024-08-30 02:36:27.958 [Warning] [ComfyUI-0/STDERR]     magic_number = pickle_module.load(f, **pickle_load_args)
2024-08-30 02:36:27.959 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-30 02:36:27.959 [Warning] [ComfyUI-0/STDERR] _pickle.UnpicklingError: invalid load key, '\x03'.
2024-08-30 02:36:27.959 [Warning] [ComfyUI-0/STDERR] 
2024-08-30 02:36:28.041 [Error] [BackendHandler] backend #0 failed to load model with error: ComfyUI execution error: invalid load key, '\x03'.
2024-08-30 02:36:28.042 [Warning] [BackendHandler] backend #0 failed to load model flux1-dev-Q8_0.gguf
2024-08-30 02:36:28.907 [Warning] [BackendHandler] All backends failed to load the model! Cannot generate anything.
2024-08-30 02:36:28.908 [Error] [BackendHandler] Backend request #1 failed: All available backends failed to load the model.
2024-08-30 02:36:28.908 [Error] [BackendHandler] Backend request #1 failed: All available backends failed to load the model.
```

**Comment by mcmonkey4eva** [comment]
Go to Utilities -> Reset All Metadata

It looks like that didn't get properly recognized as a gguf model for some reason. Usually happens from Swarm being outdated when you first add the model.

**Comment by ZeroCool22** [comment]
> Go to Utilities -> Reset All Metadata
> 
> It looks like that didn't get properly recognized as a gguf model for some reason. Usually happens from Swarm being outdated when you first add the model.

Thx.

**Comment by buzzz3d** [comment]
Did a fresh install of Swarmui, dropped a gguf file in models/diffusion_models, but I still get this error:
13:19:52.752 [Init] === SwarmUI v0.9.2.2 Starting at 2024-09-11 13:19:52 ===
13:19:52.780 [Init] Prepping extension: SwarmUI.Builtin_ScorersExtension.ScorersExtension...
13:19:52.785 [Init] Prepping extension: SwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
13:19:52.786 [Init] Prepping extension: SwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
13:19:52.786 [Init] Prepping extension: SwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
13:19:52.786 [Init] Prepping extension: SwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
13:19:52.787 [Init] Prepping extension: SwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
13:19:52.813 [Init] Parsing command line...
13:19:52.813 [Init] Loading settings file...
13:19:52.831 [Init] Re-saving settings file...
13:19:52.846 [Init] Applying command line settings...
13:19:52.865 [Init] Prepping options...
13:19:52.879 [Init] Current git commit marked as date 2024-09-09 07:43:55
13:19:52.947 [Init] CPU Cores: 24 | RAM: 63.91 GiB total, 54.47 GiB available
13:19:52.947 [Init] GPU 0: NVIDIA GeForce RTX 3090 Ti | Temp 46C | Util 4% GPU, 1% Memory | VRAM 23.99 GiB total, 22.08 GiB free, 1.67 GiB used
13:19:52.967 [Init] Loading models list...
13:19:53.091 [Init] Loading backends...
13:19:53.092 [Init] Loading backends from file...
13:19:53.094 [Init] Prepping API...
13:19:53.095 [Init] Initializing backend #0 - ComfyUI Self-Starting...
13:19:53.095 [Init] Prepping webserver...
13:19:53.098 [Init] Backend request handler loop ready...
13:19:53.200 [Init] Scan for web extensions...
13:19:53.201 [Init] Readying extensions for launch...
13:19:53.202 [Init] Launching server...
13:19:53.202 [Init] Starting webserver on http://localhost:7801
13:19:53.362 [Init] Swarm is up to date! You have version 0.9.2.2, and 0.9.2-Beta is the latest.
13:19:53.362 [Init] Program is running.
13:19:53.871 [Init] Launch web browser...
13:19:54.132 [Info] Creating new admin session 'local' for ::1
13:19:54.583 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
13:19:58.735 [Init] Self-Start ComfyUI-0 on port 7821 started.
13:20:13.555 [Info] User local requested 1 image with model 'flux1-dev-Q8_0_in_diffusion_models.gguf'...
13:20:15.819 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
13:20:15.819 [Warning] [ComfyUI-0/STDERR]   File "H:\SD\Swarmui\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 323, in execute
13:20:15.820 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
13:20:15.820 [Warning] [ComfyUI-0/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:20:15.821 [Warning] [ComfyUI-0/STDERR]   File "H:\SD\Swarmui\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 198, in get_output_data
13:20:15.821 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
13:20:15.822 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:20:15.822 [Warning] [ComfyUI-0/STDERR]   File "H:\SD\Swarmui\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 169, in _map_node_over_list
13:20:15.822 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
13:20:15.823 [Warning] [ComfyUI-0/STDERR]   File "H:\SD\Swarmui\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 158, in process_inputs
13:20:15.823 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
13:20:15.823 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:20:15.824 [Warning] [ComfyUI-0/STDERR]   File "H:\SD\Swarmui\SwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 924, in load_clip
13:20:15.824 [Warning] [ComfyUI-0/STDERR]     clip = comfy.sd.load_clip(ckpt_paths=[clip_path1, clip_path2], embedding_directory=folder_paths.get_folder_paths("embeddings"), clip_type=clip_type)
13:20:15.825 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:20:15.825 [Warning] [ComfyUI-0/STDERR]   File "H:\SD\Swarmui\SwarmUI\dlbackend\comfy\ComfyUI\comfy\sd.py", line 406, in load_clip
13:20:15.825 [Warning] [ComfyUI-0/STDERR]     clip_data.append(comfy.utils.load_torch_file(p, safe_load=True))
13:20:15.826 [Warning] [ComfyUI-0/STDERR]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:20:15.826 [Warning] [ComfyUI-0/STDERR]   File "H:\SD\Swarmui\SwarmUI\dlbackend\comfy\ComfyUI\comfy\utils.py", line 34, in load_torch_file
13:20:15.826 [Warning] [ComfyUI-0/STDERR]     sd = safetensors.torch.load_file(ckpt, device=device.type)
13:20:15.827 [Warning] [ComfyUI-0/STDERR]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:20:15.827 [Warning] [ComfyUI-0/STDERR]   File "H:\SD\Swarmui\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\safetensors\torch.py", line 313, in load_file
13:20:15.827 [Warning] [ComfyUI-0/STDERR]     with safe_open(filename, framework="pt", device=device) as f:
13:20:15.828 [Warning] [ComfyUI-0/STDERR]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:20:15.828 [Warning] [ComfyUI-0/STDERR] safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
13:20:15.828 [Warning] [ComfyUI-0/STDERR]
13:20:15.910 [Error] [BackendHandler] backend #0 failed to load model with error: ComfyUI execution error: Error while deserializing header: MetadataIncompleteBuffer
13:20:15.910 [Warning] [BackendHandler] backend #0 failed to load model flux1-dev-Q8_0_in_diffusion_models.gguf
13:20:16.583 [Warning] [BackendHandler] All backends failed to load the model! Cannot generate anything.
13:20:16.584 [Error] [BackendHandler] Backend request #1 failed: All available backends failed to load the model.
13:20:16.585 [Error] [BackendHandler] Backend request #1 failed: All available backends failed to load the model.

Any idea what I could be doing wrong? I also can't load unet models which work fine in comfy. Tried all kinds of different paths, edited the Metadata of the model, did a Utilities > Reset All Metadata and I still get this error.
Must be something simple but I don't know what to try now.

**Comment by mcmonkey4eva** [comment]
I think your `(Swarm)/Models/clip/t5xxl_enconly.safetensors` or `clip_l` file is corrupt somehow? If you close swarm, delete those files, and relaunch swarm and run again, it will autodownload those files and hopefully work then.

If that doesn't fix it, please open your own separate issue (rather than continuing to hijack this other one), and post the link generated by Server->Logs->Pastebin

**Comment by samliu315** [comment]
I tried everything but couldn't generate images using the gguf model.

**Comment by samliu315** [comment]
> I tried everything but couldn't generate images using the gguf model.我尝试了一切，但无法使用 gguf 模型生成图像。

I found this: [SwarmUI Model Support Documentation](https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Model%20Support.md#gguf-quantized-models).

To use a GGUF model, you need to do the following: Click the ☰ hamburger menu on a model, then select Edit Metadata, and set the Architecture to Flux.Dev.

**Comment by samliu315** [comment]
> I tried everything but couldn't generate images using the gguf model.

Wow, awesome! SwarmUI supports Lora for use on gguf
