### ISSUE TITLE
Lower ERROR

### ISSUE THREAD

**Issue by Maelstrom2014** [mcmonkeyprojects/SwarmUI#269]
### Your question

I use two loras, One for fast generation Hyper-FLUX.1-dev-8steps-lora for flux, second for style.
All used through buildin comfyui
```
22:58:14.265 [Warning] [ComfyUI-0/STDERR]   File "d:\ai2\SwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 158, in process_inputs
22:58:14.268 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
22:58:14.272 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:58:14.274 [Warning] [ComfyUI-0/STDERR]   File "d:\ai2\SwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 639, in load_lora
22:58:14.276 [Warning] [ComfyUI-0/STDERR]     lora = comfy.utils.load_torch_file(lora_path, safe_load=True)
22:58:14.278 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:58:14.281 [Warning] [ComfyUI-0/STDERR]   File "d:\ai2\SwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\utils.py", line 33, in load_torch_file
22:58:14.283 [Warning] [ComfyUI-0/STDERR]     if ckpt.lower().endswith(".safetensors") or ckpt.lower().endswith(".sft"):
22:58:14.303 [Warning] [ComfyUI-0/STDERR]        ^^^^^^^^^^
22:58:14.305 [Warning] [ComfyUI-0/STDERR] AttributeError: 'NoneType' object has no attribute 'lower'
22:58:14.308 [Warning] [ComfyUI-0/STDERR]
22:58:14.390 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
22:58:14.392 [Warning] [ComfyUI-0/STDERR]   File "d:\ai2\SwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 323, in execute
22:58:14.395 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
22:58:14.397 [Warning] [ComfyUI-0/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:58:14.399 [Warning] [ComfyUI-0/STDERR]   File "d:\ai2\SwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 198, in get_output_data
22:58:14.401 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
22:58:14.403 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:58:14.405 [Warning] [ComfyUI-0/STDERR]   File "d:\ai2\SwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 169, in _map_node_over_list
22:58:14.406 [Error] Grid generator hit error: ComfyUI execution error: 'NoneType' object has no attribute 'lower'
```

**Comment by mcmonkey4eva** [comment]
- Join the Swarm discord for general support https://discord.gg/q2y38cqjNw
- Make sure you're running SwarmUI, not the legacy "Stable" version
- that error indicates a model failed to load on the comfy side, the reason for this is hard to identify without more context
