### ISSUE TITLE
"--fast" argument results in platform error (_scaled_mm_out_cuda)

### ISSUE THREAD

**Issue by ScorpScorp** [mcmonkeyprojects/SwarmUI#283]
### Expected Behavior

I added "--fast" argument to the ComfyUI backend and hoped to take advantage of the supposed speed improvements for 4000 Series Nvidia cards.

![Screenshot 2024-09-25 191233](https://github.com/user-attachments/assets/65389e2b-4293-47dc-a0ae-d6f697691210)

### Actual Behavior

Unfortunately, the addition of this argument results in an error...

![Screenshot 2024-09-25 191427](https://github.com/user-attachments/assets/57d6eab0-613e-48d0-888b-ab0aaad1f69e)

### Steps to Reproduce

Add "--fast" to the ComfyUI ExtraArgs field in the Server backend.

### Debug Logs

2024-09-25 19:15:38.573 [Info] User local requested 1 image with model 'flux1-dev-fp8-compact.safetensors'...
2024-09-25 19:15:40.675 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
2024-09-25 19:15:40.675 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 323, in execute
2024-09-25 19:15:40.676 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-09-25 19:15:40.676 [Warning] [ComfyUI-0/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.677 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 198, in get_output_data
2024-09-25 19:15:40.678 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-09-25 19:15:40.678 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.679 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 169, in _map_node_over_list
2024-09-25 19:15:40.679 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
2024-09-25 19:15:40.680 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 158, in process_inputs
2024-09-25 19:15:40.680 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
2024-09-25 19:15:40.681 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.682 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyCommon\SwarmKSampler.py", line 302, in run_sampling
2024-09-25 19:15:40.682 [Warning] [ComfyUI-0/STDERR]     return self.sample(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, start_at_step, end_at_step, var_seed, var_seed_strength, sigma_max, sigma_min, rho, add_noise, return_with_leftover_noise, previews)
2024-09-25 19:15:40.683 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.683 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyCommon\SwarmKSampler.py", line 276, in sample
2024-09-25 19:15:40.684 [Warning] [ComfyUI-0/STDERR]     samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_samples,
2024-09-25 19:15:40.685 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.685 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\sample.py", line 43, in sample
2024-09-25 19:15:40.686 [Warning] [ComfyUI-0/STDERR]     samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
2024-09-25 19:15:40.687 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.687 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 829, in sample
2024-09-25 19:15:40.688 [Warning] [ComfyUI-0/STDERR]     return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
2024-09-25 19:15:40.688 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.689 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 729, in sample
2024-09-25 19:15:40.690 [Warning] [ComfyUI-0/STDERR]     return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
2024-09-25 19:15:40.690 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.691 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 716, in sample
2024-09-25 19:15:40.691 [Warning] [ComfyUI-0/STDERR]     output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
2024-09-25 19:15:40.692 [Warning] [ComfyUI-0/STDERR]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.692 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 695, in inner_sample
2024-09-25 19:15:40.693 [Warning] [ComfyUI-0/STDERR]     samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
2024-09-25 19:15:40.693 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.694 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 600, in sample
2024-09-25 19:15:40.695 [Warning] [ComfyUI-0/STDERR]     samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
2024-09-25 19:15:40.695 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.696 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
2024-09-25 19:15:40.696 [Warning] [ComfyUI-0/STDERR]     return func(*args, **kwargs)
2024-09-25 19:15:40.697 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.697 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\k_diffusion\sampling.py", line 1033, in sample_deis
2024-09-25 19:15:40.698 [Warning] [ComfyUI-0/STDERR]     denoised = model(x_cur, t_cur * s_in, **extra_args)
2024-09-25 19:15:40.699 [Warning] [ComfyUI-0/STDERR]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.699 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 299, in __call__
2024-09-25 19:15:40.700 [Warning] [ComfyUI-0/STDERR]     out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
2024-09-25 19:15:40.700 [Warning] [ComfyUI-0/STDERR]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.701 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 682, in __call__
2024-09-25 19:15:40.701 [Warning] [ComfyUI-0/STDERR]     return self.predict_noise(*args, **kwargs)
2024-09-25 19:15:40.702 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.702 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 685, in predict_noise
2024-09-25 19:15:40.703 [Warning] [ComfyUI-0/STDERR]     return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
2024-09-25 19:15:40.704 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.704 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 279, in sampling_function
2024-09-25 19:15:40.705 [Warning] [ComfyUI-0/STDERR]     out = calc_cond_batch(model, conds, x, timestep, model_options)
2024-09-25 19:15:40.706 [Warning] [ComfyUI-0/STDERR]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.706 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 228, in calc_cond_batch
2024-09-25 19:15:40.707 [Warning] [ComfyUI-0/STDERR]     output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
2024-09-25 19:15:40.707 [Warning] [ComfyUI-0/STDERR]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.708 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\model_base.py", line 142, in apply_model
2024-09-25 19:15:40.708 [Warning] [ComfyUI-0/STDERR]     model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
2024-09-25 19:15:40.709 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.710 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
2024-09-25 19:15:40.710 [Warning] [ComfyUI-0/STDERR]     return self._call_impl(*args, **kwargs)
2024-09-25 19:15:40.711 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.711 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
2024-09-25 19:15:40.712 [Warning] [ComfyUI-0/STDERR]     return forward_call(*args, **kwargs)
2024-09-25 19:15:40.713 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.713 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\ldm\flux\model.py", line 159, in forward
2024-09-25 19:15:40.714 [Warning] [ComfyUI-0/STDERR]     out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control)
2024-09-25 19:15:40.714 [Warning] [ComfyUI-0/STDERR]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.715 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\ldm\flux\model.py", line 104, in forward_orig
2024-09-25 19:15:40.715 [Warning] [ComfyUI-0/STDERR]     img = self.img_in(img)
2024-09-25 19:15:40.716 [Warning] [ComfyUI-0/STDERR]           ^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.716 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
2024-09-25 19:15:40.717 [Warning] [ComfyUI-0/STDERR]     return self._call_impl(*args, **kwargs)
2024-09-25 19:15:40.717 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.718 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
2024-09-25 19:15:40.719 [Warning] [ComfyUI-0/STDERR]     return forward_call(*args, **kwargs)
2024-09-25 19:15:40.719 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.720 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\ops.py", line 76, in forward
2024-09-25 19:15:40.720 [Warning] [ComfyUI-0/STDERR]     return self.forward_comfy_cast_weights(*args, **kwargs)
2024-09-25 19:15:40.721 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.721 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\ops.py", line 294, in forward_comfy_cast_weights
2024-09-25 19:15:40.722 [Warning] [ComfyUI-0/STDERR]     out = fp8_linear(self, input)
2024-09-25 19:15:40.722 [Warning] [ComfyUI-0/STDERR]           ^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.723 [Warning] [ComfyUI-0/STDERR]   File "C:\Users\User\Documents\StableDiffusion\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\ops.py", line 276, in fp8_linear
2024-09-25 19:15:40.723 [Warning] [ComfyUI-0/STDERR]     o = torch._scaled_mm(inn, w, out_dtype=input.dtype, bias=bias, scale_a=scale_input, scale_b=scale_weight)
2024-09-25 19:15:40.724 [Warning] [ComfyUI-0/STDERR]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 19:15:40.724 [Warning] [ComfyUI-0/STDERR] RuntimeError: _scaled_mm_out_cuda is not compiled for this platform.
2024-09-25 19:15:40.725 [Warning] [ComfyUI-0/STDERR]

**Comment by Jelosus2** [comment]
You need to upgrade the libraries related to torch. Here's how you can do so:
Open a cmd in the directory of SwarmUI then execute this commands line by line
```
cd dlbackend\comfy
python_embeded\python.exe -s -m pip install --upgrade torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu124
```

**Comment by ScorpScorp** [comment]
> You need to upgrade the libraries related to torch. Here's how you can do so: Open a cmd in the directory of SwarmUI then execute this commands line by line
> 
> ```
> cd dlbackend\comfy
> python_embeded\python.exe -s -m pip install --upgrade torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu124
> ```

Thank you Jelosus2, I will follow through with these instructions and close the issue for now. 🙏🏻
