### ISSUE TITLE
Last used time not updating submitting via API

### ISSUE THREAD

**Issue by ZiggyQubert** [mcmonkeyprojects/SwarmUI#296]
### Expected Behavior

Last used time for a comfy backend should reflect when it was last used by any means

### Actual Behavior

Last used is not updating

### Steps to Reproduce

submit a job via api

### Debug Logs

2024-10-01 13:55:43.880 [Info] Creating new admin session 'local' for 172.18.0.4 (forwarded-for: 209.51.187.143)
2024-10-01 13:55:44.163 [Debug] Was not able to redirect Comfy backend direct prompt request
2024-10-01 13:55:44.166 [Debug] [ComfyUI-0/STDERR] got prompt
2024-10-01 13:55:44.180 [Debug] ComfyUI redirection failed (outsocket): System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, WebSocketMessageFlags messageFlags, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at SwarmUI.Builtin_ComfyUIBackend.ComfyUIRedirectHelper.<>c__DisplayClass7_3.<<ComfyBackendDirectHandler>b__6>d.MoveNext() in /swarm/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIRedirectHelper.cs:line 297
2024-10-01 13:55:44.180 [Debug] ComfyUI redirection failed (outsocket): System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, WebSocketMessageFlags messageFlags, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at SwarmUI.Builtin_ComfyUIBackend.ComfyUIRedirectHelper.<>c__DisplayClass7_3.<<ComfyBackendDirectHandler>b__6>d.MoveNext() in /swarm/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIRedirectHelper.cs:line 297
2024-10-01 13:55:44.543 [Debug] [ComfyUI-0/STDERR] model weight dtype torch.float16, manual cast: None
2024-10-01 13:55:44.549 [Debug] [ComfyUI-0/STDERR] model_type EPS
2024-10-01 13:55:45.279 [Debug] [ComfyUI-0/STDERR] Using pytorch attention in VAE
2024-10-01 13:55:45.281 [Debug] [ComfyUI-0/STDERR] Using pytorch attention in VAE
2024-10-01 13:55:46.300 [Debug] [ComfyUI-0/STDERR] Requested to load SDXLClipModel
2024-10-01 13:55:46.300 [Debug] [ComfyUI-0/STDERR] Loading 1 new model
2024-10-01 13:55:46.664 [Debug] [ComfyUI-0/STDERR] loaded completely 0.0 1560.802734375 True
2024-10-01 13:55:46.853 [Debug] [ComfyUI-0/STDERR] Requested to load SDXL
2024-10-01 13:55:46.853 [Debug] [ComfyUI-0/STDERR] Loading 1 new model
2024-10-01 13:55:47.842 [Debug] [ComfyUI-0/STDERR] loaded completely 0.0 4897.0483474731445 True
2024-10-01 13:55:47.863 [Debug] [ComfyUI-0/STDERR] 
2024-10-01 13:55:48.009 [Debug] [ComfyUI-0/STDERR]   0%|          | 0/20 [00:00<?, ?it/s]
2024-10-01 13:55:48.143 [Debug] [ComfyUI-0/STDERR]   5%|▌         | 1/20 [00:00<00:02,  6.83it/s]
2024-10-01 13:55:48.291 [Debug] [ComfyUI-0/STDERR]  10%|█         | 2/20 [00:00<00:02,  7.20it/s]
2024-10-01 13:55:48.434 [Debug] [ComfyUI-0/STDERR]  15%|█▌        | 3/20 [00:00<00:02,  6.97it/s]
2024-10-01 13:55:48.572 [Debug] [ComfyUI-0/STDERR]  20%|██        | 4/20 [00:00<00:02,  7.00it/s]
2024-10-01 13:55:48.710 [Debug] [ComfyUI-0/STDERR]  25%|██▌       | 5/20 [00:00<00:02,  7.09it/s]
2024-10-01 13:55:48.847 [Debug] [ComfyUI-0/STDERR]  30%|███       | 6/20 [00:00<00:01,  7.13it/s]
2024-10-01 13:55:48.983 [Debug] [ComfyUI-0/STDERR]  35%|███▌      | 7/20 [00:00<00:01,  7.19it/s]
2024-10-01 13:55:49.122 [Debug] [ComfyUI-0/STDERR]  40%|████      | 8/20 [00:01<00:01,  7.23it/s]
2024-10-01 13:55:49.260 [Debug] [ComfyUI-0/STDERR]  45%|████▌     | 9/20 [00:01<00:01,  7.22it/s]
2024-10-01 13:55:49.395 [Debug] [ComfyUI-0/STDERR]  50%|█████     | 10/20 [00:01<00:01,  7.24it/s]
2024-10-01 13:55:49.531 [Debug] [ComfyUI-0/STDERR]  55%|█████▌    | 11/20 [00:01<00:01,  7.28it/s]
2024-10-01 13:55:49.666 [Debug] [ComfyUI-0/STDERR]  60%|██████    | 12/20 [00:01<00:01,  7.31it/s]
2024-10-01 13:55:49.804 [Debug] [ComfyUI-0/STDERR]  65%|██████▌   | 13/20 [00:01<00:00,  7.33it/s]
2024-10-01 13:55:49.940 [Debug] [ComfyUI-0/STDERR]  70%|███████   | 14/20 [00:01<00:00,  7.31it/s]
2024-10-01 13:55:50.078 [Debug] [ComfyUI-0/STDERR]  75%|███████▌  | 15/20 [00:02<00:00,  7.32it/s]
2024-10-01 13:55:50.216 [Debug] [ComfyUI-0/STDERR]  80%|████████  | 16/20 [00:02<00:00,  7.29it/s]
2024-10-01 13:55:50.350 [Debug] [ComfyUI-0/STDERR]  85%|████████▌ | 17/20 [00:02<00:00,  7.29it/s]
2024-10-01 13:55:50.486 [Debug] [ComfyUI-0/STDERR]  90%|█████████ | 18/20 [00:02<00:00,  7.33it/s]
2024-10-01 13:55:50.623 [Debug] [ComfyUI-0/STDERR]  95%|█████████▌| 19/20 [00:02<00:00,  7.34it/s]
2024-10-01 13:55:50.623 [Debug] [ComfyUI-0/STDERR] 100%|██████████| 20/20 [00:02<00:00,  7.34it/s]
2024-10-01 13:55:50.623 [Debug] [ComfyUI-0/STDERR] 100%|██████████| 20/20 [00:02<00:00,  7.25it/s]
2024-10-01 13:55:50.628 [Debug] [ComfyUI-0/STDERR] Requested to load AutoencoderKL
2024-10-01 13:55:50.628 [Debug] [ComfyUI-0/STDERR] Loading 1 new model
2024-10-01 13:55:50.657 [Debug] [ComfyUI-0/STDERR] loaded completely 0.0 159.55708122253418 True
2024-10-01 13:55:51.001 [Debug] [ComfyUI-0/STDERR] Prompt executed in 6.83 seconds

### Other

I believe this is happening in `ComfyUIRedirectHelper.cs` either its not finding the created user (in this case local) even though it created a new session, and or once it does the default redirect its not updating the necessary data

**Comment by mcmonkey4eva** [comment]
`either its not finding the created user (in this case local)`
You're bypassing Swarm's API entirely, so Swarm user is irrelevant - you're hitting the comfy API, and it's looking for a Comfy user, ie a websocket connection, which presumably you just don't have? I see in your log a failed websocket connection *after* the prompt, rather than before as you'd want. The websocket connection is where you set a client id (connect to `/ws?clientId={id}`) which you'd want to send along to the `/prompt` call as well, to link the socket and the request.

This is why you see in logs `Was not able to redirect Comfy backend direct prompt request` - you have no valid client id, so it has no idea how to link the request to anyone or anything.

The commit above should handle this case better

**Comment by ZiggyQubert** [comment]
Ok, were I'm not establishing a WS connection - due to architecture constraints at the moment - and instead am polling for status, so persumably this issue will go away if I switch to WS instead of polling

**Comment by mcmonkey4eva** [comment]
A lot of things in Comfy core API work better if you use a websocket.
The above commit should fix the issue regardless.

If you want a non-WS non-polling API, Swarm's own API - well normally uses Websocket too, but *also* has a direct HTTP API that simple delays the HTTP reply until there's a generation output to give back
