### ISSUE TITLE
SD3 use VAE error

### ISSUE THREAD

**Issue by zhenhao-huang** [mcmonkeyprojects/SwarmUI#31]
### Expected Behavior

sd3 normal use.

### Actual Behavior

Invalid operation: ComfyUI execution error: Given groups=1, weight of size [1536, 16, 2, 2], expected input[1, 4, 128, 128] to have 16 channels, but got 4 channels instead

### Steps to Reproduce

use sdxl-vae, sd-vae-ft-mse, sd-vae-ft-ema

### Debug Logs

```powershell
15:47:11.504 [Warning] WARNING: Model Stable Diffusion 3 - Medium is an SD3 model, but you have VAE sd-vae-ft-ema selected. If that VAE is not an SD3 specific VAE, this is likely a mistake. Errors may follow. If this breaks, disable the custom VAE.
15:47:18.686 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
15:47:18.687 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 151, in recursive_execute
15:47:18.688 [Warning] ComfyUI-0 on port 7821 stderr:     output_data, output_ui = get_output_data(obj, input_data_all)
15:47:18.689 [Warning] ComfyUI-0 on port 7821 stderr:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.690 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 81, in get_output_data
15:47:18.691 [Warning] ComfyUI-0 on port 7821 stderr:     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
15:47:18.694 [Warning] ComfyUI-0 on port 7821 stderr:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.695 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 74, in map_node_over_list
15:47:18.695 [Warning] ComfyUI-0 on port 7821 stderr:     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
15:47:18.696 [Warning] ComfyUI-0 on port 7821 stderr:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.697 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyCommon\SwarmKSampler.py", line 298, in run_sampling
15:47:18.697 [Warning] ComfyUI-0 on port 7821 stderr:     return self.sample(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, start_at_step, end_at_step, var_seed, var_seed_strength, sigma_max, sigma_min, rho, add_noise, return_with_leftover_noise, previews)
15:47:18.698 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.699 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyCommon\SwarmKSampler.py", line 271, in sample
15:47:18.700 [Warning] ComfyUI-0 on port 7821 stderr:     samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_samples,
15:47:18.701 [Warning] ComfyUI-0 on port 7821 stderr:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.701 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\sample.py", line 43, in sample
15:47:18.702 [Warning] ComfyUI-0 on port 7821 stderr:     samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
15:47:18.703 [Warning] ComfyUI-0 on port 7821 stderr:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.704 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 795, in sample
15:47:18.718 [Warning] ComfyUI-0 on port 7821 stderr:     return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
15:47:18.719 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.721 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 697, in sample
15:47:18.722 [Warning] ComfyUI-0 on port 7821 stderr:     return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
15:47:18.723 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.723 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 684, in sample
15:47:18.724 [Warning] ComfyUI-0 on port 7821 stderr:     output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
15:47:18.725 [Warning] ComfyUI-0 on port 7821 stderr:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.741 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 663, in inner_sample
15:47:18.757 [Warning] ComfyUI-0 on port 7821 stderr:     samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
15:47:18.774 [Warning] ComfyUI-0 on port 7821 stderr:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.775 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 568, in sample
15:47:18.776 [Warning] ComfyUI-0 on port 7821 stderr:     samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
15:47:18.792 [Warning] ComfyUI-0 on port 7821 stderr:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.803 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
15:47:18.804 [Warning] ComfyUI-0 on port 7821 stderr:     return func(*args, **kwargs)
15:47:18.805 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^
15:47:18.805 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\k_diffusion\sampling.py", line 599, in sample_dpmpp_2m
15:47:18.806 [Warning] ComfyUI-0 on port 7821 stderr:     denoised = model(x, sigmas[i] * s_in, **extra_args)
15:47:18.807 [Warning] ComfyUI-0 on port 7821 stderr:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.807 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 291, in __call__
15:47:18.808 [Warning] ComfyUI-0 on port 7821 stderr:     out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
15:47:18.809 [Warning] ComfyUI-0 on port 7821 stderr:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.835 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 650, in __call__
15:47:18.837 [Warning] ComfyUI-0 on port 7821 stderr:     return self.predict_noise(*args, **kwargs)
15:47:18.839 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.840 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 653, in predict_noise
15:47:18.841 [Warning] ComfyUI-0 on port 7821 stderr:     return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
15:47:18.842 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.854 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 277, in sampling_function
15:47:18.869 [Warning] ComfyUI-0 on port 7821 stderr:     out = calc_cond_batch(model, conds, x, timestep, model_options)
15:47:18.872 [Warning] ComfyUI-0 on port 7821 stderr:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.873 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 226, in calc_cond_batch
15:47:18.874 [Warning] ComfyUI-0 on port 7821 stderr:     output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
15:47:18.875 [Warning] ComfyUI-0 on port 7821 stderr:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.875 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\model_base.py", line 113, in apply_model
15:47:18.902 [Warning] ComfyUI-0 on port 7821 stderr:     model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
15:47:18.903 [Warning] ComfyUI-0 on port 7821 stderr:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.906 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
15:47:18.906 [Warning] ComfyUI-0 on port 7821 stderr:     return self._call_impl(*args, **kwargs)
15:47:18.907 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.908 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
15:47:18.909 [Warning] ComfyUI-0 on port 7821 stderr:     return forward_call(*args, **kwargs)
15:47:18.910 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.910 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\ldm\modules\diffusionmodules\mmdit.py", line 961, in forward
15:47:18.935 [Warning] ComfyUI-0 on port 7821 stderr:     return super().forward(x, timesteps, context=context, y=y)
15:47:18.936 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.939 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\ldm\modules\diffusionmodules\mmdit.py", line 937, in forward
15:47:18.940 [Warning] ComfyUI-0 on port 7821 stderr:     x = self.x_embedder(x) + self.cropped_pos_embed(hw, device=x.device).to(dtype=x.dtype, device=x.device)
15:47:18.941 [Warning] ComfyUI-0 on port 7821 stderr:         ^^^^^^^^^^^^^^^^^^
15:47:18.942 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
15:47:18.972 [Warning] ComfyUI-0 on port 7821 stderr:     return self._call_impl(*args, **kwargs)
15:47:18.973 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.974 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
15:47:18.975 [Warning] ComfyUI-0 on port 7821 stderr:     return forward_call(*args, **kwargs)
15:47:18.975 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:18.989 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\ldm\modules\diffusionmodules\mmdit.py", line 113, in forward
15:47:18.990 [Warning] ComfyUI-0 on port 7821 stderr:     x = self.proj(x)
15:47:18.991 [Warning] ComfyUI-0 on port 7821 stderr:         ^^^^^^^^^^^^
15:47:18.992 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
15:47:19.002 [Warning] ComfyUI-0 on port 7821 stderr:     return self._call_impl(*args, **kwargs)
15:47:19.003 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:19.011 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
15:47:19.014 [Warning] ComfyUI-0 on port 7821 stderr:     return forward_call(*args, **kwargs)
15:47:19.015 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:19.016 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\ops.py", line 80, in forward
15:47:19.017 [Warning] ComfyUI-0 on port 7821 stderr:     return super().forward(*args, **kwargs)
15:47:19.017 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:19.018 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
15:47:19.019 [Warning] ComfyUI-0 on port 7821 stderr:     return self._conv_forward(input, self.weight, self.bias)
15:47:19.019 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:19.020 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\hzh\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
15:47:19.021 [Warning] ComfyUI-0 on port 7821 stderr:     return F.conv2d(input, weight, bias, self.stride,
15:47:19.022 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:47:19.022 [Warning] ComfyUI-0 on port 7821 stderr: RuntimeError: Given groups=1, weight of size [1536, 16, 2, 2], expected input[1, 4, 128, 128] to have 16 channels, but got 4 channels instead
15:47:19.023 [Warning] ComfyUI-0 on port 7821 stderr:
```

**Comment by mcmonkey4eva** [comment]
You cannot use an SDXL VAE on SD3, as SD3 has a 16-channel latent space and a brand new VAE to support it, vs SDXL had a 4-channel latent space.

The SD3 native VAE is much more powerful than SDXL VAEs were.
