### ISSUE TITLE
Installation: Error handling API request '/API/InstallConfirmWS'

### ISSUE THREAD

**Issue by SeriousM** [mcmonkeyprojects/SwarmUI#33]
### Expected Behavior

Installation with "just install" and all options on default should just install SwarmUI

### Actual Behavior

```log
[WebAPI] Error handling API request '/API/InstallConfirmWS' for user 'local': Internal exception: System.IO.IOException: Cannot create 'T:\StableStudio\SwarmUI\dlbackend\comfy' because a file or directory with the same name already exists.
```

### Steps to Reproduce

System:
- Win11 (22631.3737)
- dotnet8 installed
- SwarmUI v0.9.0.1

- clone `https://github.com/mcmonkeyprojects/SwarmUI.git`
- open `launch-windows.bat`

Log output:
```log
The system cannot find the path specified.
""
""
"WARNING: You did a git pull without building. Will now build for you..."
""
""
The system cannot find the path specified.
The system cannot find the file specified.
error: The source specified has already been added to the list of available package sources. Provide a unique source.


Usage: dotnet nuget add source [arguments] [options]

Arguments:
  PackageSourcePath  Path to the package source.

Options:
  -n|--name                       Name of the source.
  -u|--username                   Username to be used when connecting to an authenticated source.
  -p|--password                   Password to be used when connecting to an authenticated source.
  --store-password-in-clear-text  Enables storing portable package source credentials by disabling password encryption.
  --valid-authentication-types    Comma-separated list of valid authentication types for this source. Set this to basic if the server advertises NTLM or Negotiate and your credentials must be sent using the Basic mechanism, for instance when using a PAT with on-premises Azure DevOps Server. Other valid values include negotiate, kerberos, ntlm, and digest, but these values are unlikely to be useful.
  --protocol-version              The NuGet server protocol version to be used. Currently supported versions are 2 and 3. See https://learn.microsoft.com/nuget/api/overview for information about the version 3 protocol. Defaults to 2 if not specified.
  --configfile                    The NuGet configuration file. If specified, only the settings from this file will be used. If not specified, the hierarchy of configuration files from the current directory will be used. For more information, see https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior.
  -h|--help                       Show help information

  Determining projects to restore...
  Restored T:\StableStudio\SwarmUI\src\SwarmUI.csproj (in 512 ms).
  SwarmUI -> T:\StableStudio\SwarmUI\src\bin\live_release\SwarmUI.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.95
01:15:50.578 [Init] === SwarmUI v0.9.0.1 Starting at 2024-06-28 01:15:50 ===
01:15:50.702 [Init] Prepping extension: SwarmUI.Builtin_ScorersExtension.ScorersExtension...
01:15:50.711 [Init] Prepping extension: SwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
01:15:50.712 [Init] Prepping extension: SwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
01:15:50.713 [Init] Prepping extension: SwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
01:15:50.714 [Init] Prepping extension: SwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
01:15:50.715 [Init] Prepping extension: SwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
01:15:50.756 [Init] Parsing command line...
01:15:50.757 [Init] Loading settings file...
01:15:50.758 [Init] No settings file found.
01:15:50.759 [Init] Re-saving settings file...
01:15:50.781 [Init] Applying command line settings...
01:15:50.953 [Init] Prepping options...
01:15:50.974 [Init] Current git commit marked as date 2024-06-27 20:09:06
01:15:51.029 [Init] Swarm is up to date! Version 0.9.0.1 is the latest.
01:15:51.133 [Init] Loading models list...
01:15:51.154 [Init] Loading backends...
01:15:51.156 [Init] Loading backends from file...
01:15:51.158 [Init] Prepping API...
01:15:51.159 [Init] Backend request handler loop ready...
01:15:51.161 [Init] Prepping webserver...
01:15:51.198 [Init] CPU Cores: 12 | RAM: 31.92 GiB total, 17.83 GiB available
01:15:51.199 [Init] GPU 0: NVIDIA GeForce RTX 3060 Ti | Temp 38C | Util 27% GPU, 31% Memory | VRAM 8.00 GiB total, 6.52 GiB free, 1.32 GiB used
01:15:51.316 [Init] Scan for web extensions...
01:15:51.321 [Init] Readying extensions for launch...
01:15:51.322 [Init] Launching server...
01:15:51.324 [Init] Starting webserver on http://localhost:7801
01:15:51.380 [Init] Program is running.
01:15:51.887 [Init] Launch web browser to install page...
01:15:52.427 [Info] Creating new admin session 'local' for ::1
01:15:57.101 [Init] [Installer] Installation request received, processing...
01:15:57.103 [Init] [Installer] Setting theme to modern_dark.
01:15:57.104 [Init] [Installer] Configuring settings as 'just yourself' install.
01:15:57.105 [Init] [Installer] Downloading ComfyUI backend... please wait...
01:18:39.373 [Init] [Installer] Downloaded! Extracting... (look in terminal window for details)

7-Zip (a) 23.01 (x86) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20

Scanning the drive for archives:
1 file, 1551835100 bytes (1480 MiB)

Extracting archive: dlbackend\comfyui_dl.7z
--
Path = dlbackend\comfyui_dl.7z
Type = 7z
Physical Size = 1551835100
Headers Size = 361598
Method = LZMA:25 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 2932
Files: 29282
Size:       5721481652
Compressed: 1551835100
01:21:17.142 [Error] [WebAPI] Error handling API request '/API/InstallConfirmWS' for user 'local': Internal exception: System.IO.IOException: Cannot create 'T:\StableStudio\SwarmUI\dlbackend\comfy' because a file or directory with the same name already exists.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath, Boolean _)
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at SwarmUI.WebAPI.BasicAPIFeatures.<InstallConfirmWS>g__moveFolder|3_2() in T:\StableStudio\SwarmUI\src\WebAPI\BasicAPIFeatures.cs:line 187
   at SwarmUI.WebAPI.BasicAPIFeatures.InstallConfirmWS(Session session, WebSocket socket, String theme, String installed_for, String backend, String models, Boolean install_amd, String language) in T:\StableStudio\SwarmUI\src\WebAPI\BasicAPIFeatures.cs:line 210
   at SwarmUI.WebAPI.API.HandleAsyncRequest(HttpContext context) in T:\StableStudio\SwarmUI\src\WebAPI\API.cs:line 124

```

### Debug Logs

```powershell
There is no running server, therefor now logs available.
```

**Comment by mcmonkey4eva** [comment]
You seem to be installing into a folder that swarm is already installed into?

You can manually delete the folders `dlbackend` and `Data` if you want to do a clean reinstall in-place

**Comment by SeriousM** [comment]
Not intentionally, but you're right.
The first install attempts was interrupted because of too less space left.
Then I tried a git cleanup which wasn't cleaning up the submodules (dlbackend content) and any other install attempt failed because of the already existing ComfyUI folder).
