### ISSUE TITLE
Pulled latest git code with "update-windows.bat" today, now I get python error upon launch

### ISSUE THREAD

**Issue by nikolatesla20** [mcmonkeyprojects/SwarmUI#342]
### Expected Behavior

It shouldn't error out. 

### Actual Behavior

It pukes on an error sayinig "main.py : 'bool' object has not attribute 'split"

![image](https://github.com/user-attachments/assets/57131fb6-0328-4c3b-b418-2cab1121cb26)

I tried restarting the Swarm UI again and this time it just hung up entirely on the Comfy backend startup

### Steps to Reproduce

have previous version on your system , then run update-windows.bat, then try running Swarm UI

### Debug Logs

2024-10-21 19:38:25.637 [Init] === SwarmUI v0.9.3.1 Starting at 2024-10-21 19:38:25 ===
2024-10-21 19:38:25.671 [Init] Prepping extension: SwarmUI.Builtin_ScorersExtension.ScorersExtension...
2024-10-21 19:38:25.672 [Init] Prepping extension: SwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
2024-10-21 19:38:25.673 [Init] Prepping extension: SwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
2024-10-21 19:38:25.674 [Init] Prepping extension: SwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
2024-10-21 19:38:25.674 [Init] Prepping extension: SwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
2024-10-21 19:38:25.675 [Init] Prepping extension: SwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
2024-10-21 19:38:25.705 [Init] Parsing command line...
2024-10-21 19:38:25.706 [Init] Loading settings file...
2024-10-21 19:38:25.720 [Init] Re-saving settings file...
2024-10-21 19:38:25.737 [Init] Applying command line settings...
2024-10-21 19:38:25.758 [Init] Prepping options...
2024-10-21 19:38:25.853 [Init] CPU Cores: 16 | RAM: 31.91 GiB total, 18.49 GiB available, 128.00 GiB virtual, 96.09 GiB swap
2024-10-21 19:38:25.854 [Init] GPU 0: NVIDIA GeForce RTX 3090 | Temp 42C | Util 42% GPU, 25% Memory | VRAM 24.00 GiB total, 22.74 GiB free, 1.01 GiB used
2024-10-21 19:38:25.863 [Init] Loading models list...
2024-10-21 19:38:25.895 [Init] Loading backends...
2024-10-21 19:38:25.896 [Init] Loading backends from file...
2024-10-21 19:38:25.898 [Init] Prepping API...
2024-10-21 19:38:25.899 [Init] Initializing backend #0 - ComfyUI Self-Starting...
2024-10-21 19:38:25.900 [Init] Prepping webserver...
2024-10-21 19:38:25.902 [Init] Backend request handler loop ready...
2024-10-21 19:38:26.001 [Init] Scan for web extensions...
2024-10-21 19:38:26.003 [Init] Readying extensions for launch...
2024-10-21 19:38:26.003 [Init] Launching server...
2024-10-21 19:38:26.004 [Init] Starting webserver on http://0.0.0.0:7801
2024-10-21 19:38:26.403 [Init] Current git commit marked as date 2024-10-20 09:20:20
2024-10-21 19:38:26.423 [Init] Swarm is up to date! You have version 0.9.3.1, and 0.9.3-Beta is the latest.
2024-10-21 19:38:26.424 [Init] Program is running.
2024-10-21 19:38:26.934 [Init] Launch web browser...
2024-10-21 19:38:27.440 [Info] Creating new admin session 'local' for 127.0.0.1
2024-10-21 19:38:27.442 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
2024-10-21 19:38:32.544 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):

**Comment by nikolatesla20** [comment]
Here are debug logs when it crashes:

2024-10-21 19:41:03.907 [Init] GPU 0: NVIDIA GeForce RTX 3090 | Temp 43C | Util 13% GPU, 18% Memory | VRAM 24.00 GiB total, 22.70 GiB free, 1.05 GiB used
2024-10-21 19:41:03.920 [Init] Loading models list...
2024-10-21 19:41:03.952 [Init] Loading backends...
2024-10-21 19:41:03.953 [Init] Loading backends from file...
2024-10-21 19:41:03.956 [Init] Prepping API...
2024-10-21 19:41:03.957 [Init] Initializing backend #0 - ComfyUI Self-Starting...
2024-10-21 19:41:03.958 [Init] Prepping webserver...
2024-10-21 19:41:03.960 [Init] Backend request handler loop ready...
2024-10-21 19:41:04.055 [Init] Scan for web extensions...
2024-10-21 19:41:04.058 [Init] Readying extensions for launch...
2024-10-21 19:41:04.059 [Init] Launching server...
2024-10-21 19:41:04.059 [Init] Starting webserver on http://0.0.0.0:7801
2024-10-21 19:41:04.325 [Init] Swarm is up to date! You have version 0.9.3.1, and 0.9.3-Beta is the latest.
2024-10-21 19:41:04.326 [Init] Program is running.
2024-10-21 19:41:04.835 [Init] Launch web browser...
2024-10-21 19:41:05.318 [Info] Creating new admin session 'local' for 127.0.0.1
2024-10-21 19:41:05.340 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
2024-10-21 19:41:10.523 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
2024-10-21 19:41:10.524 [Warning] [ComfyUI-0/STDERR]   File "C:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\main.py", line 225, in <module>
2024-10-21 19:41:10.525 [Warning] [ComfyUI-0/STDERR]     load_extra_path_config(config_path)
2024-10-21 19:41:10.525 [Warning] [ComfyUI-0/STDERR]   File "C:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\main.py", line 190, in load_extra_path_config
2024-10-21 19:41:10.526 [Warning] [ComfyUI-0/STDERR]     for y in conf[x].split("\n"):
2024-10-21 19:41:10.527 [Warning] [ComfyUI-0/STDERR]              ^^^^^^^^^^^^^
2024-10-21 19:41:10.528 [Warning] [ComfyUI-0/STDERR] AttributeError: 'bool' object has no attribute 'split'
2024-10-21 19:41:10.928 [Info] Self-Start ComfyUI-0 unexpectedly exited (if something failed, change setting `LogLevel` to `Debug` to see why!)
2024-10-21 19:41:10.929 [Info] Self-Start ComfyUI-0 had errors before shutdown:
[ComfyUI-0/STDERR] Total VRAM 24575 MB, total RAM 32672 MB
[ComfyUI-0/STDERR] pytorch version: 2.3.1+cu121
[ComfyUI-0/STDERR] Set vram state to: NORMAL_VRAM
[ComfyUI-0/STDERR] Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
[ComfyUI-0/STDERR] Using pytorch cross attention
[ComfyUI-0/STDERR] [Prompt Server] web root: C:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.2.47
[ComfyUI-0/STDERR] Traceback (most recent call last):
[ComfyUI-0/STDERR]   File "C:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\main.py", line 225, in <module>
[ComfyUI-0/STDERR]     load_extra_path_config(config_path)
[ComfyUI-0/STDERR]   File "C:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\main.py", line 190, in load_extra_path_config
[ComfyUI-0/STDERR]     for y in conf[x].split("\n"):
[ComfyUI-0/STDERR]              ^^^^^^^^^^^^^
[ComfyUI-0/STDERR] AttributeError: 'bool' object has no attribute 'split'

**Comment by nikolatesla20** [comment]
Going back to git version commit/896f8321c8bbf2342177e9b73add587a3b7acda1 and it runs properly again
