### ISSUE TITLE
ERROR : Entry Point liborchaudio.pyd 

### ISSUE THREAD

**Issue by JumpingFlash0001** [mcmonkeyprojects/SwarmUI#359]
### Expected Behavior

Hello, the torchaudio have an error, and I don't know why

Thanks for the support.

### Actual Behavior

![image](https://github.com/user-attachments/assets/2137c18a-f1c6-4d18-b5fd-42d68e6df353)

### Steps to Reproduce

I have just launch the launch-windows.bat

### Debug Logs

2024-10-26 22:37:14.253 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
2024-10-26 22:37:14.254 [Warning] [ComfyUI-0/STDERR]   File "E:\SD\SwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 2006, in load_custom_node
2024-10-26 22:37:14.254 [Warning] [ComfyUI-0/STDERR]     module_spec.loader.exec_module(module)
2024-10-26 22:37:14.255 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-10-26 22:37:14.255 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-10-26 22:37:14.256 [Warning] [ComfyUI-0/STDERR]   File "E:\SD\SwarmUI\dlbackend\comfy\ComfyUI\comfy_extras\nodes_audio.py", line 1, in <module>
2024-10-26 22:37:14.256 [Warning] [ComfyUI-0/STDERR]     import torchaudio
2024-10-26 22:37:14.257 [Warning] [ComfyUI-0/STDERR]   File "E:\SD\SwarmUI\dlbackend\comfy\python_embeded\lib\site-packages\torchaudio\__init__.py", line 2, in <module>
2024-10-26 22:37:14.257 [Warning] [ComfyUI-0/STDERR]     from . import _extension  # noqa  # usort: skip
2024-10-26 22:37:14.257 [Warning] [ComfyUI-0/STDERR]   File "E:\SD\SwarmUI\dlbackend\comfy\python_embeded\lib\site-packages\torchaudio\_extension\__init__.py", line 38, in <module>
2024-10-26 22:37:14.258 [Warning] [ComfyUI-0/STDERR]     _load_lib("libtorchaudio")
2024-10-26 22:37:14.258 [Warning] [ComfyUI-0/STDERR]   File "E:\SD\SwarmUI\dlbackend\comfy\python_embeded\lib\site-packages\torchaudio\_extension\utils.py", line 60, in _load_lib
2024-10-26 22:37:14.259 [Warning] [ComfyUI-0/STDERR]     torch.ops.load_library(path)
2024-10-26 22:37:14.259 [Warning] [ComfyUI-0/STDERR]   File "E:\SD\SwarmUI\dlbackend\comfy\python_embeded\lib\site-packages\torch\_ops.py", line 1295, in load_library
2024-10-26 22:37:14.259 [Warning] [ComfyUI-0/STDERR]     ctypes.CDLL(path)
2024-10-26 22:37:14.260 [Warning] [ComfyUI-0/STDERR]   File "ctypes\__init__.py", line 374, in __init__
2024-10-26 22:37:14.260 [Warning] [ComfyUI-0/STDERR] OSError: [WinError 127] La procÚdure spÚcifiÚe est introuvable
2024-10-26 22:37:14.261 [Warning] [ComfyUI-0/STDERR] 

### Other

I have relaunch the update_comfyui_and_python_dependencies.bat but this is not repair.

**Comment by mcmonkey4eva** [comment]
This is an issue with AMD DirectML, you can just ignore it.

Alternately, if you want better AMD support
(A) swap to Linux
(B) use WSL
(C) install Zluda to replace DirectML
