### ISSUE TITLE
User settings and Lora/Model Issue when loading

### ISSUE THREAD

**Issue by MykT33** [mcmonkeyprojects/SwarmUI#362]
### Your question

I thought SwarmUI would be great...but it's not.  Namely, i cant tell it where i want the generations to be placed(SAVED).  Also, i have THOUSANDS of loras/embeddings/models that have spaces in them, and they wont load and crashes.  I MEAN WOW...  Why do i have to rename thousands of files when ever other UI can use them just fine no matter how they are named.  PLUS, when it was loading the folders i placed to manually point to them, the program was pulling from and comparing my database to one from Civitai!!!  thats a serious issue when i didn't tell it to do this.  I DONT want my database compromised and it looks like that this UI was doing it.  WHY was it verifying my models/loras/embeddings?

### Other

I am rally hopeful that these issues will be addressed as this UI looks REALLY PROMISING! thanks for all your hard work!

**Comment by MykT33** [comment]
Apologies, if i came across rude!  NOT MY INTENTIONS.  

I have used ComfyUI with spaces in my embedding names/folders/etc.. and have never had an error.  It is throwing errors for loras and emb's.  Here is one example out of hundreds-thousands that it is throwing out.

[Warning] Error handling metadata database for model Q:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\loras/PONY\Concept Art Style SDXL_LoRA_Pony Diffusion V6 XL.safetensors: System.IO.IOException: Insufficient system resources exist to complete the requested service. : 'Q:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\loras\PONY\model_metadata.ldb'
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Upsert(T entity)
   at SwarmUI.Text2Image.T2IModelHandler.LoadMetadata(T2IModel model) in T:\Swarm_UI\SwarmUI\src\Text2Image\T2IModelHandler.cs:line 322

hundreds of these types for the emb's:  

21:27:05.126 [Warning] Embedding model 'PONY TI/eznegativexl.safetensors' contains spaces in its name, which will cause it to not parse properly on the backend. Please rename the file or folder to remove spaces.

I am seeing no spaces, but i do have spaces in the folders, and i have MANY folders that some do have spaces.

I am running i9-14900ks / RTX-4090 / 128GB DDR5 RAM

**Comment by mcmonkey4eva** [comment]
That LoRA error is unrelated to spaces. I think your data drive is full?

The embedding errors are real errors - ComfyUI doesn't give an error message for it, it just silently fails to load the embedding :( that's why I added a warning in Swarm, so you wouldn't think you're using the embedding but actually it's doing nothing. For things like negative embeds it can be really hard to tell whether it's working or not since they're designed to make subtle changes, thus the need for a special warning message to let you know.
And yes the folder name `PONY TI` having a space means... there's a space.

For reference, in the ComfyUI input, your prompt box will have something like `prompt words here words words embedding:PONY TI/eznegativexl.safetensors words words words`, and Comfy splits that by spaces and compares each option for if it starts with `embedding:` and if so, looks for a file with the name after that part, so it will find `embedding:PONY` and fail to load an embedding named `PONY`, and then it will see the word `TI/eznegativexl.safetensors` and treat that as just prompt text, not an embedding at all.
If you just did eg `embedding:eznegativexl.safetensors` it will see the `embedding:` but the filename `eznegativexl.safetensors` will be invalid, as you don't have a file named that inside the embeddings folder, you have a file *in a subfolder* that it doesn't know to look for unless it's written explicitly as part of the name.

**Comment by MykT33** [comment]
I use M2's for my drives 4-8TB ones, and they have enough space (at least 400GB-1TB left on most of them).  for the reading of emb's, when it does that in comfy, i found that just removing the subfolder it actually works as intended even though it's in a sub folder.  i just delete the PONY TI/ in front of the embedding.  it does give the error if i forget to remove it, but they work as intended if i just remove the subfolder reference!!  Odd but at least it works, so i just kept them in the subfolder in Comfy so they are easier to find for each different model usage.

For the reset metadata, (the warning reference you give) it isn't going to change anything on my drives right?  like delete loras/emb info etc, and or the images i have next to the (named exactly as the lora/emb) for reference.  

ALSO, i always have a same-named Txt file next to it as i place important info, like triggers, prompts, and extra data the creator uses.  In comfy when i have a txt file next to it (same name as the item) it pulls it up in a secondary box that i could copy and paste the info i needed.  VERY convenient!!

I know you cant do that for triggers (multiple ones to pick from as you have stated this would be difficult) unless you could somehow make your own reference file (like .info or similar) that it could "auto place triggers" when it loads the lora/emb?

ORRR more simply, have it load an area in the info section that you already have for each item where as long as the txt file is named the exact same as the item then it will place it into a BOX (at the bottom maybe?) and then the user can just paste what they want from the .txt (.info) file.

This could be a solution to many issues or requests i've seen, and for my own item id love to see in your product.  this would give the user at least an option to manually place items where they want, like active prompts/triggers and the like.

2nd:  Is there a way to utilize the COMFY yaml file that points to all the locations for better setup?  It would be great once you select COMFY as a backend, it would PULL the yaml file automatically and fill in the locations, or copy them into your yaml I saw in data folder in Swarm.  Also i didn't see a location pointing to upscalers.  Might have missed it somewhere, but didn't see it in the list, but did see it in the yaml file.

Thanks again for your help.  So far i am liking what I'm seeing from your product.  I'm pretty good with Comfy, but this gives us a plug and play feel!

**Comment by mcmonkey4eva** [comment]
`For the reset metadata, (the warning reference you give) it isn't going to change anything on my drives right? like delete loras/emb info etc, and or the images i have next to the (named exactly as the lora/emb) for reference.`
That won't delete any of your files, that will delete and rebuild Swarm's model metadata database, the file it uses to load model lists quicker (ie without having to read every file again to see what's in it every time you launch swarm)

`ORRR more simply, have it load an area in the info section that you already have for each item where as long as the txt file is named the exact same as the item then it will place it into a BOX (at the bottom maybe?) and then the user can just paste what they want from the .txt (.info) file.`
This is called model metadata, Swarm supports it better than any other UI, just click "Edit Metadata" on the model and type in whatever you want in whatever part you want.

The automated trigger limitation is just that if you set an automatic trigger, you have to pick one. If you have multiple... well it's not automatic anymore is it? it's manual. Bit redundant to have an automatic system that just automatically... tells you to go do it manually.

`2nd: Is there a way to utilize the COMFY yaml file that points to all the locations for better setup?`
Model paths are configured in the UI under Server Configuration

**Comment by MykT33** [comment]
Thanks for the reply.  I have thousands of Models! lol. it would take forever to copy it all over in the Edit Metadata,  couldn't it have the ability to just read it from the already made txt file i created for them all?  

Sorry, might have not explained the Comfy yaml file.  I have multiple locations on separate drives, so i manually edited the yaml file for Comfy to manually point to these locations so Comfy can find them.  As it is, i have to re-enter each location.  This is not hard to do but wanted a simple solution; as i still use comfy for crazy templates and sometimes i re-edit the yaml file to point to a new location.  So if Swarm could just PULL those changes from the Comfy yaml, it would be more convenient is what i'm trying to convey.

**Comment by MykT33** [comment]
Just for lora's i have over 3500!

**Comment by brendanhoar** [comment]
The space in the embed path thing is another you say potato I say potahhhto issue.

Many people consider file*name* and file*path* different things, and so the error being _Embedding model 'PONY TI/eznegativexl.safetensors' contains spaces in its *name*_ leads to confusion.

Changing "name" to "name or path" (or something similar) will help understanding.
