### ISSUE TITLE
Specified t5xxl_fp16.safetensors and it still wanted to download and use t5xxl_enconly.safetensors

### ISSUE THREAD

**Issue by Jonseed** [mcmonkeyprojects/SwarmUI#407]
### Expected Behavior

I expected it to use the t5xxl_fp16.safetensors I already have in text encoders folder, and that I specified in the UI (I turned on the T5xxl model switch, and chose the t5xxl_fp16.safetensors from the dropdown menu). 

### Actual Behavior

When I clicked generate, the logs say they didn't find the t5xxl_enconly.safetensors and it is currently downloading it.

### Steps to Reproduce

Explained above. Why didn't it use the t5xxl_fp16 I specified in the UI?

### Debug Logs

!!! Exception during processing !!! No such file or directory: "D:/repos/stable-diffusion-webui/models\\text_encoder\\t5xxl_enconly.safetensors"
2024-11-10 19:19:37.710 [Warning] [ComfyUI-2/STDERR] Traceback (most recent call last):
2024-11-10 19:19:37.711 [Warning] [ComfyUI-2/STDERR]   File "D:\repos\ComfyUI\execution.py", line 323, in execute
2024-11-10 19:19:37.711 [Warning] [ComfyUI-2/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-11-10 19:19:37.712 [Warning] [ComfyUI-2/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10 19:19:37.713 [Warning] [ComfyUI-2/STDERR]   File "D:\repos\ComfyUI\execution.py", line 198, in get_output_data
2024-11-10 19:19:37.714 [Warning] [ComfyUI-2/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-11-10 19:19:37.714 [Warning] [ComfyUI-2/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10 19:19:37.715 [Warning] [ComfyUI-2/STDERR]   File "D:\repos\ComfyUI\execution.py", line 169, in _map_node_over_list
2024-11-10 19:19:37.716 [Warning] [ComfyUI-2/STDERR]     process_inputs(input_dict, i)
2024-11-10 19:19:37.717 [Warning] [ComfyUI-2/STDERR]   File "D:\repos\ComfyUI\execution.py", line 158, in process_inputs
2024-11-10 19:19:37.717 [Warning] [ComfyUI-2/STDERR]     results.append(getattr(obj, func)(**inputs))
2024-11-10 19:19:37.718 [Warning] [ComfyUI-2/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10 19:19:37.719 [Warning] [ComfyUI-2/STDERR]   File "D:\repos\ComfyUI\nodes.py", line 937, in load_clip
2024-11-10 19:19:37.720 [Warning] [ComfyUI-2/STDERR]     clip = comfy.sd.load_clip(ckpt_paths=[clip_path1, clip_path2], embedding_directory=folder_paths.get_folder_paths("embeddings"), clip_type=clip_type)
2024-11-10 19:19:37.721 [Warning] [ComfyUI-2/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10 19:19:37.721 [Warning] [ComfyUI-2/STDERR]   File "D:\repos\ComfyUI\comfy\sd.py", line 437, in load_clip
2024-11-10 19:19:37.722 [Warning] [ComfyUI-2/STDERR]     clip_data.append(comfy.utils.load_torch_file(p, safe_load=True))
2024-11-10 19:19:37.723 [Warning] [ComfyUI-2/STDERR]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10 19:19:37.723 [Warning] [ComfyUI-2/STDERR]   File "D:\repos\ComfyUI\comfy\utils.py", line 34, in load_torch_file
2024-11-10 19:19:37.724 [Warning] [ComfyUI-2/STDERR]     sd = safetensors.torch.load_file(ckpt, device=device.type)
2024-11-10 19:19:37.725 [Warning] [ComfyUI-2/STDERR]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10 19:19:37.725 [Warning] [ComfyUI-2/STDERR]   File "D:\repos\conda-envs\comfy\Lib\site-packages\safetensors\torch.py", line 313, in load_file
2024-11-10 19:19:37.726 [Warning] [ComfyUI-2/STDERR]     with safe_open(filename, framework="pt", device=device) as f:
2024-11-10 19:19:37.727 [Warning] [ComfyUI-2/STDERR]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10 19:19:37.727 [Warning] [ComfyUI-2/STDERR] FileNotFoundError: No such file or directory: "D:/repos/stable-diffusion-webui/models\\text_encoder\\t5xxl_enconly.safetensors"
2024-11-10 19:19:37.728 [Warning] [ComfyUI-2/STDERR] 
2024-11-10 19:19:37.729 [Debug] [ComfyUI-2/STDERR] Prompt executed in 5.13 seconds
2024-11-10 19:19:38.003 [Error] [BackendHandler] backend #2 failed to load model with error: ComfyUI execution error: No such file or directory: "D:/repos/stable-diffusion-webui/models\\text_encoder\\t5xxl_enconly.safetensors"
2024-11-10 19:19:38.005 [Warning] [BackendHandler] backend #2 failed to load model flux/flux1-dev-Q8_0.gguf
2024-11-10 19:19:38.006 [Debug] Will deny backends: 2
2024-11-10 19:19:38.432 [Warning] [BackendHandler] All backends failed to load the model 'D:/repos/stable-diffusion-webui/models/diffusion_models/flux\flux1-dev-Q8_0.gguf'! Cannot generate anything.
2024-11-10 19:19:38.435 [Error] [BackendHandler] Backend request #1 failed: All available backends failed to load the model 'D:/repos/stable-diffusion-webui/models/diffusion_models/flux\flux1-dev-Q8_0.gguf'.
2024-11-10 19:19:38.437 [Error] [BackendHandler] Backend request #1 failed: All available backends failed to load the model 'D:/repos/stable-diffusion-webui/models/diffusion_models/flux\flux1-dev-Q8_0.gguf'.
2024-11-10 19:19:38.439 [Debug] [BackendHandler] Backend request #1 finished.
2024-11-10 19:19:38.440 [Debug] Refused to generate image for local: All available backends failed to load the model 'D:/repos/stable-diffusion-webui/models/diffusion_models/flux\flux1-dev-Q8_0.gguf'.
2024-11-10 19:19:58.924 [Info] t5xxl_enconly.safetensors download at 5.0%...

### Other

If I import the workflow into the Comfy Workflow tab, it shows my t5xxl_fp16.safetensors in the dual clip loader. So I'm not sure why it is defaulting to this other t5xxl_enconly.safetensors file that I don't already have.

**Comment by Jonseed** [comment]
If I queue the job from the Comfy Workflow tab, it works fine, using the t5xxl_fp16 file specified.

**Comment by Jonseed** [comment]
I'm still getting this error, where it wants to download t5xxl_enconly even though I've specified t5xxl_fp16. I've tried specifying other t5 quants, and they don't work either.

**Comment by mcmonkey4eva** [comment]
Yes it's a valid bug, it's just low priority. The correct file you specified is used, it just also requires enconly be valid and usable for preload. It's low priority because this only affects people who are intentionally overfilling their ram with fp16, ie people who won't care if swarm is accidentally using a bit of extra resources on the enconly file too. If you care about resource consumption you'll naturally prefer the file that isn't twice the size for no reason.

**Comment by Jonseed** [comment]
The problem is that it won't even generate an image without the enconly file present. It has to download the entire 4.7gb enconly file before generating _anything_ when I have a valid fp16 t5 already specified (or any other t5).

I'm not sure what you mean about overfilling ram with fp16 "for no reason," since fp16 produces more accurate images than fp8:
https://github.com/city96/ComfyUI-GGUF/pull/49#issuecomment-2308566998

**Comment by DocShotgun** [comment]
I got around this by creating a symlink called `t5xxl_enconly.safetensors` that points to my pre-existing t5xxl. Not ideal but it works without taking up extra disk space I suppose.

**Comment by mcmonkey4eva** [comment]
Swarm now will try to use your selected textenc models when loading for normal gens. If you trigger a contextless load (eg hit the "Load Model Now") button, it will still want to grab default models. You should still ideally have a model named t5xxl_enconly to serve as global default.
