### ISSUE TITLE
Error using flux1-redux image prompting/Style Model - CLIPVisionEncode.encode() missing 'crop' argument

### ISSUE THREAD

**Issue by deeplearner5** [mcmonkeyprojects/SwarmUI#446]
### Expected Behavior

I'm trying to used flux1-redux-dev as a style model with flux1-dev as main model; a) I'm dragging taking an existing pic to main screen, b) clicking More->Use as Image Prompt (which makes the Image Prompting options appear on the left), and selecting flux1-redux-dev from the Use Style Model dropdown. As per docs, I'm setting Style Model Apply Start to 0.2, but when I try to generate, I get the issue below. I've re-tried with/without Use Reference Only option, and various pics, models etc.

### Actual Behavior

The generation fails, with the error in the Debug Logs below.

### Steps to Reproduce

As above.

### Debug Logs

2024-11-29 17:37:53.094 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
2024-11-29 17:37:53.095 [Warning] [ComfyUI-0/STDERR]   File "E:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 323, in execute
2024-11-29 17:37:53.095 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-11-29 17:37:53.096 [Warning] [ComfyUI-0/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-29 17:37:53.096 [Warning] [ComfyUI-0/STDERR]   File "E:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 198, in get_output_data
2024-11-29 17:37:53.097 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-11-29 17:37:53.097 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-29 17:37:53.098 [Warning] [ComfyUI-0/STDERR]   File "E:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 169, in _map_node_over_list
2024-11-29 17:37:53.098 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
2024-11-29 17:37:53.099 [Warning] [ComfyUI-0/STDERR]   File "E:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 158, in process_inputs
2024-11-29 17:37:53.100 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
2024-11-29 17:37:53.101 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-29 17:37:53.101 [Warning] [ComfyUI-0/STDERR] TypeError: CLIPVisionEncode.encode() missing 1 required positional argument: 'crop'
2024-11-29 17:37:53.102 [Warning] [ComfyUI-0/STDERR] 

### Other

This may just me being unclear on how to use the flux1-redux-dev model correctly, and if so, apologies.

**Comment by deeplearner5** [comment]
Great stuff, many thanks for sorting.
