### ISSUE TITLE
Android Termux Permission denied error

### ISSUE THREAD

**Issue by KintCark** [mcmonkeyprojects/SwarmUI#47]
I got past the dot net stuff. Now I'm getting permission denied error any way to fix this on linux? Please respond asap. I hope this works:)

Unhandled exception. System.Net.NetworkInformation.NetworkInformationException (13): An error was encountered while querying information from the operating system. ---> System.UnauthorizedAccessException: Access to the path '/proc/net/tcp' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at System.Net.NetworkInformation.StringParsingHelpers.ReadAllText(String filePath)
   at System.Net.NetworkInformation.StringParsingHelpers.ReadAllText(String filePath)
   at System.Net.NetworkInformation.StringParsingHelpers.ParseActiveTcpListenersFromFiles(String tcp4ConnectionsFile, String tcp6ConnectionsFile)
   at SwarmUI.Utils.Utilities.IsPortTaken(Int32 port) in /root/SwarmUI/src/Utils/Utilities.cs:line 480
   at SwarmUI.Core.Program.ApplyCommandLineSettings() in /root/SwarmUI/src/Core/Program.cs:line 506
   at SwarmUI.Core.Program.Main(String[] args) in /root/SwarmUI/src/Core/Program.cs:line 123
./launch-linux.sh: line 47:  1173 Aborted                 dotnet src/bin/live_release/SwarmUI.dll $@

**Comment by mcmonkey4eva** [comment]
This is still your Android thing right? https://github.com/mcmonkeyprojects/SwarmUI/issues/46

That's beyond me, Android isn't going to work - as I said before, you need a desktop PC with a GPU. I don't know what you're hoping to accomplish bruteforcing Swarm onto an Android phone.

**Comment by KintCark** [comment]
Yea it doesn't work on termux so ima try sdfx hehehe

**Comment by mcmonkey4eva** [comment]
You understand Stable Diffusion requires a GPU right? Like a graphics card? Generally that'd be specifically a high-end nvidia one, not even an old one or from AMD/intel/etc???

**Comment by KintCark** [comment]
Nope I've already achieved several stable-diffusion-webui  on Termux I have a high end phone it can run everything!! Check out my github page: KintCark

**Comment by mcmonkey4eva** [comment]
That's ... terrifying.

Well I mean if you really want to get it working I suppose anything is possible, but, yeah, I'm not gonna be able to help diagnose issues here
