### ISSUE TITLE
Models fail to load "The text encoders (CLIP) failed to load"

### ISSUE THREAD

**Issue by siriume** [mcmonkeyprojects/SwarmUI#472]
### Expected Behavior

load model normal.

### Actual Behavior

failed to load model.

### Steps to Reproduce

Download model [PixelWave Flux.1-dev 03](https://huggingface.co/mikeyandfriends/PixelWave_FLUX.1-dev_03/blob/main/pixelwave_flux1_dev_fp8_03.safetensors) fp8 version or [here](https://civitai.com/models/141592?modelVersionId=992642), then load.
try to modify clip-l, t5xxl and Dtype , but bug still exists.

### Debug Logs

```
19:52:16.126 [Info] User local requested 1 image with model 'Flux/pixelwave_flux1_dev_fp8_03.safetensors'...
19:52:16.150 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
19:52:16.151 [Warning] [ComfyUI-0/STDERR]   File "dev/comfyui/execution.py", line 323, in execute
19:52:16.151 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
19:52:16.151 [Warning] [ComfyUI-0/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
19:52:16.151 [Warning] [ComfyUI-0/STDERR]   File "dev/comfyui/execution.py", line 198, in get_output_data
19:52:16.151 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
19:52:16.151 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
19:52:16.151 [Warning] [ComfyUI-0/STDERR]   File "dev/comfyui/execution.py", line 169, in _map_node_over_list
19:52:16.151 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
19:52:16.151 [Warning] [ComfyUI-0/STDERR]   File "dev/comfyui/execution.py", line 158, in process_inputs
19:52:16.151 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
19:52:16.151 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
19:52:16.151 [Warning] [ComfyUI-0/STDERR]   File "dev/swarmui/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyCommon/SwarmInternalUtil.py", line 48, in just_load
19:52:16.152 [Warning] [ComfyUI-0/STDERR]     raise ValueError("The text encoders (CLIP) failed to load")
19:52:16.152 [Warning] [ComfyUI-0/STDERR] ValueError: The text encoders (CLIP) failed to load
19:52:16.152 [Warning] [ComfyUI-0/STDERR] 
19:52:16.375 [Error] [BackendHandler] backend #0 failed to load model with error: ComfyUI execution error: The text encoders (CLIP) failed to load
19:52:16.375 [Warning] [BackendHandler] backend #0 failed to load model Flux/pixelwave_flux1_dev_fp8_03.safetensors
19:52:17.129 [Warning] [BackendHandler] All backends failed to load the model 'dev/swarmui/Models/Stable-Diffusion/Flux/pixelwave_flux1_dev_fp8_03.safetensors'! Cannot generate anything.
19:52:17.129 [Error] [BackendHandler] Backend request #7 failed: All available backends failed to load the model 'dev/swarmui/Models/Stable-Diffusion/Flux/pixelwave_flux1_dev_fp8_03.safetensors'.
19:52:17.129 [Error] [BackendHandler] Backend request #7 failed: All available backends failed to load the model 'dev/swarmui/Models/Stable-Diffusion/Flux/pixelwave_flux1_dev_fp8_03.safetensors'.

```

**Comment by mcmonkey4eva** [comment]
That's a backbone-only model, it needs to be in the `diffusion_models` folder instead of the usual stable-diffusion models folder
