### ISSUE TITLE
can't select other models for segmentation

### ISSUE THREAD

**Issue by Joshua19770704** [mcmonkeyprojects/SwarmUI#497]
### Your question

Hi, dear mcmonkey, the default segmentation is fine, but I can't select other models for segmentation, just as follow: 

![{DC0F85BC-2F77-462D-AE49-331BC80C8DD7}](https://github.com/user-attachments/assets/3bba306f-55fa-4216-b124-778e7f4aa785)
![{5E021981-D9DB-455A-8211-57B2E5963F4C}](https://github.com/user-attachments/assets/dea31cad-2831-4e8a-b354-b3e70f860848)

![{A28BAEB7-0908-4D41-9FED-9D8064D70AF5}](https://github.com/user-attachments/assets/2bba40e9-9bca-450d-9d32-2237ac6c7d92)
![{BB6D1E51-52AC-4BE4-B622-1AB0B3C763EB}](https://github.com/user-attachments/assets/1b05ed93-5997-4f96-bdc6-69aed92aa96b)

How should we solve this problem?

### Logs

2024-12-30 21:40:46.244 [Info] User local requested 1 image with model 'Flux/flux1-FP8-dev.safetensors'...
2024-12-30 21:40:46.316 [Warning] [ComfyUI-0/STDERR] !!! Exception during processing !!! ERROR: Could not detect model type of: D:\SUPER_SD\ComfyUI-aki-v1.3\models\ultralytics\segm\face_yolov8m-seg_60.pt
2024-12-30 21:40:46.317 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
2024-12-30 21:40:46.317 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\execution.py", line 327, in execute
2024-12-30 21:40:46.317 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-12-30 21:40:46.317 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\execution.py", line 202, in get_output_data
2024-12-30 21:40:46.318 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-12-30 21:40:46.318 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\execution.py", line 174, in _map_node_over_list
2024-12-30 21:40:46.318 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
2024-12-30 21:40:46.319 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\execution.py", line 163, in process_inputs
2024-12-30 21:40:46.319 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
2024-12-30 21:40:46.319 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\nodes.py", line 568, in load_checkpoint
2024-12-30 21:40:46.320 [Warning] [ComfyUI-0/STDERR]     out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
2024-12-30 21:40:46.320 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\comfy\sd.py", line 828, in load_checkpoint_guess_config
2024-12-30 21:40:46.320 [Warning] [ComfyUI-0/STDERR]     raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
2024-12-30 21:40:46.320 [Warning] [ComfyUI-0/STDERR] RuntimeError: ERROR: Could not detect model type of: D:\SUPER_SD\ComfyUI-aki-v1.3\models\ultralytics\segm\face_yolov8m-seg_60.pt

2024-12-30 21:40:46.321 [Warning] [ComfyUI-0/STDERR] 
2024-12-30 21:42:41.933 [Info] User local requested 1 image with model 'Flux/flux1-FP8-dev.safetensors'...
2024-12-30 21:42:44.036 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
2024-12-30 21:42:44.037 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\execution.py", line 327, in execute
2024-12-30 21:42:44.037 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-12-30 21:42:44.037 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\execution.py", line 202, in get_output_data
2024-12-30 21:42:44.038 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-12-30 21:42:44.039 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\execution.py", line 174, in _map_node_over_list
2024-12-30 21:42:44.039 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
2024-12-30 21:42:44.039 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\execution.py", line 163, in process_inputs
2024-12-30 21:42:44.040 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
2024-12-30 21:42:44.040 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\nodes.py", line 568, in load_checkpoint
2024-12-30 21:42:44.040 [Warning] [ComfyUI-0/STDERR]     out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
2024-12-30 21:42:44.041 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\comfy\sd.py", line 825, in load_checkpoint_guess_config
2024-12-30 21:42:44.041 [Warning] [ComfyUI-0/STDERR]     sd = comfy.utils.load_torch_file(ckpt_path)
2024-12-30 21:42:44.041 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\comfy\utils.py", line 45, in load_torch_file
2024-12-30 21:42:44.042 [Warning] [ComfyUI-0/STDERR]     pl_sd = torch.load(ckpt, map_location=device, pickle_module=comfy.checkpoint_pickle)
2024-12-30 21:42:44.042 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Subpack\modules\subcore.py", line 52, in torch_wrapper
2024-12-30 21:42:44.042 [Warning] [ComfyUI-0/STDERR]     return orig_torch_load(*args, **kwargs)
2024-12-30 21:42:44.042 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\ultralytics\utils\patches.py", line 86, in torch_load
2024-12-30 21:42:44.043 [Warning] [ComfyUI-0/STDERR]     return _torch_load(*args, **kwargs)
2024-12-30 21:42:44.043 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\torch\serialization.py", line 1360, in load
2024-12-30 21:42:44.043 [Warning] [ComfyUI-0/STDERR]     return _load(
2024-12-30 21:42:44.043 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\torch\serialization.py", line 1848, in _load
2024-12-30 21:42:44.043 [Warning] [ComfyUI-0/STDERR]     result = unpickler.load()
2024-12-30 21:42:44.044 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\torch\serialization.py", line 1837, in find_class
2024-12-30 21:42:44.044 [Warning] [ComfyUI-0/STDERR]     return super().find_class(mod_name, name)
2024-12-30 21:42:44.044 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\comfy\checkpoint_pickle.py", line 13, in find_class
2024-12-30 21:42:44.044 [Warning] [ComfyUI-0/STDERR]     return super().find_class(module, name)
2024-12-30 21:42:44.045 [Warning] [ComfyUI-0/STDERR] ModuleNotFoundError: No module named 'ultralytics.yolo'

**Comment by mcmonkey4eva** [comment]
So problem 1 is you've super wonked your model paths

Your `ModelRoot` should be eg `Models` or `C:/my-comfy-path/models`, and `SDModelFolder` set to eg `checkpoints` or `Stable-Diffusion` to indicate that ModelRoot/checkpoints is where the SD Models go

You appear to have it currently set such that your root is used as an sdmodelfolder, so you're able to select entirely nonsensical files from the models list. This is very wrong.

Problem 2 stems from the random things you're trying based on those misconfigurations. Yolo models go in Root/ `yolov8` as it says in the docs @ https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/Features/Prompt%20Syntax.md#automatic-segmentation-and-refining

Then you use it... the way it says to in the docs, or by selecting the yolo model in the segment interface accessed by clicking the `+` button next to the problem box

**Comment by Joshua19770704** [comment]
Right, "Segment Model" is for the base model, I misunderstood it. I thought we could choose the yolo model here.

 After I placed the yolo model in "\SwarmUI\Models\yolov8" folder, and replace the text with yolo-model name in the prompt, I can use the yolo model for segmentation. 

But where is " by selecting the yolo model in the segment interface accessed by clicking the + button next to the problem box"? Could you send me an image to illustrate it? 

And how to "insert a <lora:...> inside the prompt area of the segment to have a lora model apply onto that segment""? Like this?

<segment<lora:...>:yolo-face_yolov8m-seg_60.pt-1,0.8,1>, or something else? Please explain in detail. Thanks a lot.

**Comment by mcmonkey4eva** [comment]
> But where is " by selecting the yolo model in the segment interface accessed by clicking the + button next to the problem box"? Could you send me an image to illustrate it?

![image](https://github.com/user-attachments/assets/edf3521b-5e21-496a-b47a-5b66c56f7f13)

followed by
![image](https://github.com/user-attachments/assets/54720d90-0df1-48a6-a2f7-3cf29d90ea36)

-------------------

> And how to "insert a lora:... inside the prompt area of the segment to have a lora model apply onto that segment""? Like this?
> <segmentlora:...:yolo-face_yolov8m-seg_60.pt-1,0.8,1>, or something else? Please explain in detail. Thanks a lot.

wat? no

`<segment:whatever> some prompt here <lora:mylora>`

**Comment by Joshua19770704** [comment]
I put my yolo models in "SwarmUI\Models\yolov8”, but I can't find them is here
![{E847B648-6AB5-457A-83FA-EE9873DC96FF}](https://github.com/user-attachments/assets/b6b6cc7a-118a-45b1-8d35-8b756b665a67)
Where Should I put them?

**Comment by mcmonkey4eva** [comment]
you may need to refresh the page for the list to update

**Comment by Joshua19770704** [comment]
I refreshed the page, they didn't show up, even I restarted the SwarmUI, the still did not show up. So what's the problem?

**Comment by Joshua19770704** [comment]
And these promps didn't work too, did I miss something?

<segment:face,0.6,0.5> photo of OHX <lora:Flux/OHX20to25_3> 
<segment:face,0.6,0.5> photo of OHX <lora:Flux/OHX20to25_3:1> 
<segment:face,0.6,0.5> photo of OHX <lora:Flux/OHX20to25_3:0.9>
