### ISSUE TITLE
Grid Generator for loras raises exception when lora is in prompt

### ISSUE THREAD

**Issue by Lawrr** [mcmonkeyprojects/SwarmUI#70]
### Expected Behavior

Grid generator runs sucessfully.

### Actual Behavior

Grid generator stops with an exception.

### Steps to Reproduce

1. Use a prompt that includes an inline lora (e.g. `<lora:foo>`) in the prompt
2. Enable the grid generator with a single lora (or any number) in the grid parameters
3. Hit generate grid
4. Grid generation fails with exception

### Debug Logs

```powershell
21:15:22.938 [Error] Grid Generator hit error: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SwarmUI.Text2Image.T2IParamInput.<>c.<.cctor>b__8_11(String data, PromptTagContext context) in C:\Folders\StableDiffusion\SwarmUI\src\Text2Image\T2IParamInput.cs:line 378
   at SwarmUI.Text2Image.T2IParamInput.<>c__DisplayClass29_1.<ProcessPromptLike>b__1(String tag) in C:\Folders\StableDiffusion\SwarmUI\src\Text2Image\T2IParamInput.cs:line 671
   at FreneticUtilities.FreneticToolkit.StringConversionHelper.QuickSimpleTagFiller(String taggedText, String prefix, String suffix, Func`2 tagReader, Boolean doSubtags, Int32 maxRecurse)
   at SwarmUI.Text2Image.T2IParamInput.ProcessPromptLike(String val, PromptTagContext context) in C:\Folders\StableDiffusion\SwarmUI\src\Text2Image\T2IParamInput.cs:line 695
   at SwarmUI.Text2Image.T2IParamInput.ProcessPromptLike(T2IRegisteredParam`1 param) in C:\Folders\StableDiffusion\SwarmUI\src\Text2Image\T2IParamInput.cs:line 640
   at SwarmUI.Text2Image.T2IParamInput.PreparsePromptLikes() in C:\Folders\StableDiffusion\SwarmUI\src\Text2Image\T2IParamInput.cs:line 578
   at SwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in C:\Folders\StableDiffusion\SwarmUI\src\Text2Image\T2IEngine.cs:line 221
   at SwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages) in C:\Folders\StableDiffusion\SwarmUI\src\Text2Image\T2IEngine.cs:line 144
   --- End of inner exception stack trace ---
21:15:22.941 [Error] GridGen stopped while running: {
  "error": "Failed due to internal error."
}
```

### Other

* Works fine if the grid generator is for a list of models instead of a list of loras
* Works fine if there is a lora selected in the "Current Loras" list (even though it does not get applied to the grid -- not actually sure if this is expected, but separate issue)

**Comment by mcmonkey4eva** [comment]
The root issue here is `Loras` parameter _must_ pair with `Lora Weights`, if you don't use them together, it won't work.

Alternately you can use loras entirely in prompt with prompt replace, which is arguably more convenient anyway.

The commit pushed above corrects the specific null error there, but doesn't fix that the lora param doesn't work without the lora weights param matching it

**Comment by Lawrr** [comment]
I've had the `Loras` parameter work before without the `Lora Weights` parameters in the grid, hence my confusion. It seemed like it just defaulted the weights to 1 (although looking at the generated images now, it seems like when you do this, loraweights is missing from the metadata). Sounds like this isn't the intended way to use it based on your explanation.

> Works fine if there is a lora selected in the "Current Loras" list

Digging into this a bit more, seems like the reason this "fixes" it is because it takes the weight from the lora in the "Current Loras" list and applies it as the grid's `Lora Weights` parameter, which seems like an unexpected interaction.

Fwiw after the commit, using the same reproduction steps, I now get a different error:
```
14:46:19.642 [Error] Internal error processing T2I request: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SwarmUI.Builtin_ComfyUIBackend.WorkflowGenerator.LoadLorasForConfinement(Int32 confinement, JArray model, JArray clip) in C:\Folders\StableDiffusion\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\WorkflowGenerator.cs:line 246
   at SwarmUI.Builtin_ComfyUIBackend.WorkflowGeneratorSteps.<>c.<Register>b__2_2(WorkflowGenerator g) in C:\Folders\StableDiffusion\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\WorkflowGeneratorSteps.cs:line 108
   at SwarmUI.Builtin_ComfyUIBackend.WorkflowGenerator.CreateStandardModelLoader(T2IModel model, String type, String id, Boolean noCascadeFix) in C:\Folders\StableDiffusion\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\WorkflowGenerator.cs:line 613
   at SwarmUI.Builtin_ComfyUIBackend.WorkflowGeneratorSteps.<>c.<Register>b__2_0(WorkflowGenerator g) in C:\Folders\StableDiffusion\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\WorkflowGeneratorSteps.cs:line 55
   at SwarmUI.Builtin_ComfyUIBackend.WorkflowGenerator.Generate() in C:\Folders\StableDiffusion\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\WorkflowGenerator.cs:line 407
   at SwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.CreateWorkflow(T2IParamInput user_input, Func`2 initImageFixer, String ModelFolderFormat, HashSet`1 features) in C:\Folders\StableDiffusion\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 652
   at SwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput) in C:\Folders\StableDiffusion\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 726
   at SwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in C:\Folders\StableDiffusion\SwarmUI\src\Text2Image\T2IEngine.cs:line 264
14:46:19.644 [Error] Grid generator hit error: Something went wrong while generating images.
14:46:20.645 [Error] GridGen stopped while running: {
  "error": "Something went wrong while generating images."
}
```
but it does fix itself if I add the `Lora Weights` parameters.

Should this be checked on the server explicitly that those two parameters are paired together and raise an explicit error otherwise? Seems like something easy to not know about (also given the fact it currently _just works_ without lora weights set [when there's no lora inlined in the prompt anyway]). Seems it can cause some strange interactions and errors like the above if the user uses it in unintended ways and leads it to an invalid state?

**Comment by mcmonkey4eva** [comment]
With new commit it now will give a warning on mismatch and also pre-correct it before it touches prompt parsing
