### ISSUE TITLE
Unable to use the SwarmLoraLoader node in a custom workflow while not having any lora listed

### ISSUE THREAD

**Issue by derrian-distro** [mcmonkeyprojects/SwarmUI#84]
### Expected Behavior

To still generate the image while there is no lora to load

### Actual Behavior

Fails to generate any image with an error message

### Steps to Reproduce

1.) load this [workflow](https://github.com/user-attachments/files/16326066/workflow.json), which uses nothing but base comfy and swarm nodes
2.) click "Use This Workflow in Generate Tab"
3.) try to generate anything while not having a lora loaded
4.) error message

### Debug Logs

```powershell
2024-07-21 16:55:49.752 [Debug] [Load Time] Initial settings load took 0.11s (0.11s from start)
2024-07-21 16:55:49.764 [Debug] [Load Time] Extension PreInit took 0.02s (0.13s from start)
2024-07-21 16:55:49.828 [Debug] [Load Time] Prep Objects took 0.06s (0.19s from start)
2024-07-21 16:55:49.828 [Debug] [Load Time] Web PreInit took 0s (0.19s from start)
2024-07-21 16:55:49.832 [Debug] [Load Time] Extensions Init took 0s (0.19s from start)
2024-07-21 16:55:49.833 [Debug] [Load Time] Prep Utils took 0s (0.19s from start)
2024-07-21 16:55:49.861 [Debug] [Load Time] Languages load took 0.03s (0.22s from start)
2024-07-21 16:55:50.135 [Debug] [Load Time] Model listing took 0.27s (0.49s from start)
2024-07-21 16:55:50.139 [Debug] [Load Time] Backends took 0.02s (0.5s from start)
2024-07-21 16:55:50.140 [Debug] [Load Time] API took 0s (0.5s from start)
2024-07-21 16:55:50.192 [Debug] [Load Time] [Web] WebApp builder prep took 0.05s (0.05s from start)
2024-07-21 16:55:50.237 [Debug] [Load Time] [Web] WebApp build took 0.05s (0.09s from start)
2024-07-21 16:55:50.237 [Debug] [Load Time] [Web] exception handler took 0s (0.09s from start)
2024-07-21 16:55:50.237 [Debug] [Load Time] [Web] StartStop handler took 0s (0.09s from start)
2024-07-21 16:55:50.237 [Debug] [Load Time] [Web] static files took 0s (0.09s from start)
2024-07-21 16:55:50.286 [Debug] [Load Time] [Web] core use calls took 0.05s (0.14s from start)
2024-07-21 16:55:50.288 [Debug] [Load Time] [Web] core maps took 0s (0.14s from start)
2024-07-21 16:55:50.291 [Debug] [Load Time] [Web] end took 0s (0.14s from start)
2024-07-21 16:55:50.291 [Debug] [Load Time] Web prep took 0.14s (0.64s from start)
2024-07-21 16:55:50.292 [Debug] [Load Time] Extensions pre-launch took 0s (0.64s from start)
2024-07-21 16:55:50.324 [Debug] [Load Time] Web launch took 0.03s (0.67s from start)
2024-07-21 16:55:50.872 [Debug] Comfy node pull response for sd-dynamic-thresholding: Already up to date.
2024-07-21 16:55:50.874 [Debug] Comfy node pull response for ComfyUI-SAI_API: Already up to date.
2024-07-21 16:55:50.903 [Debug] Comfy git pull response: Already up to date.
2024-07-21 16:55:51.506 [Debug] Comfy node pull response for ComfyUI-SAI_API: Already up to date.
2024-07-21 16:55:51.511 [Debug] Comfy node pull response for sd-dynamic-thresholding: Already up to date.
2024-07-21 16:55:51.513 [Debug] Requested generic launch of dlbackend/comfy/ComfyUI/main.py on GPU 0 from ComfyUI-0
2024-07-21 16:55:51.515 [Debug] (ComfyUI-0 launch) Adding path F:\ai_stuff\SwarmUI\dlbackend\comfy\python_embeded
2024-07-21 16:55:51.515 [Debug] (ComfyUI-0 launch) Will use python: F:\ai_stuff\SwarmUI\dlbackend\comfy\python_embeded\python.exe
2024-07-21 16:55:51.909 [Debug] [ComfyUI-0/STDOUT] [START] Security scan
2024-07-21 16:55:52.843 [Debug] [ComfyUI-0/STDOUT] [DONE] Security scan
2024-07-21 16:55:52.992 [Debug] [ComfyUI-0/STDOUT] ## ComfyUI-Manager: installing dependencies done.
2024-07-21 16:55:52.992 [Debug] [ComfyUI-0/STDOUT] ** ComfyUI startup time: 2024-07-21 16:55:52.991370
2024-07-21 16:55:52.992 [Debug] [ComfyUI-0/STDOUT] ** Platform: Windows
2024-07-21 16:55:52.992 [Debug] [ComfyUI-0/STDOUT] ** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
2024-07-21 16:55:52.993 [Debug] [ComfyUI-0/STDOUT] ** Python executable: F:\ai_stuff\SwarmUI\dlbackend\comfy\python_embeded\python.exe
2024-07-21 16:55:52.993 [Debug] [ComfyUI-0/STDOUT] ** ComfyUI Path: F:\ai_stuff\SwarmUI\dlbackend\comfy\ComfyUI
2024-07-21 16:55:52.993 [Debug] [ComfyUI-0/STDOUT] ** Log path: F:\ai_stuff\SwarmUI\dlbackend\comfy\comfyui.log
2024-07-21 16:55:52.995 [Debug] [ComfyUI-0/STDOUT] 
2024-07-21 16:55:52.995 [Debug] [ComfyUI-0/STDOUT] Prestartup times for custom nodes:
2024-07-21 16:55:52.996 [Debug] [ComfyUI-0/STDOUT]    1.4 seconds: F:\ai_stuff\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager
2024-07-21 16:55:52.997 [Debug] [ComfyUI-0/STDOUT] 
2024-07-21 16:55:54.382 [Debug] [ComfyUI-0/STDERR] Total VRAM 49140 MB, total RAM 65277 MB
2024-07-21 16:55:54.383 [Debug] [ComfyUI-0/STDERR] pytorch version: 2.3.1+cu121
2024-07-21 16:55:54.383 [Debug] [ComfyUI-0/STDERR] Set vram state to: NORMAL_VRAM
2024-07-21 16:55:54.383 [Debug] [ComfyUI-0/STDERR] Device: cuda:0 NVIDIA RTX A6000 : cudaMallocAsync
2024-07-21 16:55:55.269 [Debug] [ComfyUI-0/STDERR] Using pytorch cross attention
2024-07-21 16:55:56.246 [Debug] [ComfyUI-0/STDERR] [Prompt Server] web root: F:\ai_stuff\SwarmUI\dlbackend\comfy\ComfyUI\web
2024-07-21 16:55:56.249 [Debug] [ComfyUI-0/STDERR] Adding extra search path checkpoints F:\ai_stuff\SwarmUI\Models\Stable-Diffusion
2024-07-21 16:55:56.249 [Debug] [ComfyUI-0/STDERR] Adding extra search path vae F:\ai_stuff\SwarmUI\Models\VAE
2024-07-21 16:55:56.249 [Debug] [ComfyUI-0/STDERR] Adding extra search path vae F:\ai_stuff\SwarmUI\Models\VAE
2024-07-21 16:55:56.249 [Debug] [ComfyUI-0/STDERR] Adding extra search path loras F:\ai_stuff\SwarmUI\Models\Lora
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path loras F:\ai_stuff\SwarmUI\Models\Lora
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path loras F:\ai_stuff\SwarmUI\Models\LyCORIS
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path upscale_models F:\ai_stuff\SwarmUI\Models\ESRGAN
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path upscale_models F:\ai_stuff\SwarmUI\Models\RealESRGAN
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path upscale_models F:\ai_stuff\SwarmUI\Models\SwinIR
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path upscale_models F:\ai_stuff\SwarmUI\Models\upscale-models
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path upscale_models F:\ai_stuff\SwarmUI\Models\upscale_models
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path embeddings F:\ai_stuff\SwarmUI\Models\Embeddings
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path embeddings F:\ai_stuff\SwarmUI\Models\embeddings
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path hypernetworks F:\ai_stuff\SwarmUI\Models\hypernetworks
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path controlnet F:\ai_stuff\SwarmUI\Models\controlnet
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path controlnet F:\ai_stuff\SwarmUI\Models\ControlNet
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path clip_vision F:\ai_stuff\SwarmUI\Models\clip_vision
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path clip_vision F:\ai_stuff\SwarmUI\Models\clip_vision
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path clip F:\ai_stuff\SwarmUI\Models\clip
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path unet F:\ai_stuff\SwarmUI\Models\unet
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path gligen F:\ai_stuff\SwarmUI\Models\gligen
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path ipadapter F:\ai_stuff\SwarmUI\Models\ipadapter
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path yolov8 F:\ai_stuff\SwarmUI\Models\yolov8
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path tensorrt F:\ai_stuff\SwarmUI\Models\tensorrt
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path clipseg F:\ai_stuff\SwarmUI\Models\clipseg
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path custom_nodes F:\ai_stuff\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes
2024-07-21 16:55:56.250 [Debug] [ComfyUI-0/STDERR] Adding extra search path custom_nodes F:\ai_stuff\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes
2024-07-21 16:55:56.681 [Debug] [ComfyUI-0/STDOUT] ### Loading: ComfyUI-Manager (V2.46.3)
2024-07-21 16:55:56.851 [Debug] [ComfyUI-0/STDOUT] ### ComfyUI Revision: 2386 [f836e693] | Released on '2024-07-21'
2024-07-21 16:55:57.077 [Debug] [ComfyUI-0/STDOUT] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2024-07-21 16:55:57.087 [Debug] [ComfyUI-0/STDOUT] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2024-07-21 16:55:57.097 [Debug] [ComfyUI-0/STDOUT] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2024-07-21 16:55:57.148 [Debug] [ComfyUI-0/STDOUT] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2024-07-21 16:55:57.163 [Debug] [ComfyUI-0/STDOUT] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2024-07-21 16:55:58.282 [Debug] [ComfyUI-0/STDERR] 
2024-07-21 16:55:58.282 [Debug] [ComfyUI-0/STDERR] Import times for custom nodes:
2024-07-21 16:55:58.283 [Debug] [ComfyUI-0/STDERR]    0.0 seconds: F:\ai_stuff\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\websocket_image_save.py
2024-07-21 16:55:58.283 [Debug] [ComfyUI-0/STDERR]    0.0 seconds: F:\ai_stuff\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Logic
2024-07-21 16:55:58.283 [Debug] [ComfyUI-0/STDERR]    0.0 seconds: F:\ai_stuff\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes\sd-dynamic-thresholding
2024-07-21 16:55:58.283 [Debug] [ComfyUI-0/STDERR]    0.0 seconds: F:\ai_stuff\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes\ComfyUI-SAI_API
2024-07-21 16:55:58.283 [Debug] [ComfyUI-0/STDERR]    0.1 seconds: F:\ai_stuff\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyCommon
2024-07-21 16:55:58.283 [Debug] [ComfyUI-0/STDERR]    0.3 seconds: F:\ai_stuff\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager
2024-07-21 16:55:58.283 [Debug] [ComfyUI-0/STDERR]    1.2 seconds: F:\ai_stuff\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyExtra
2024-07-21 16:55:58.283 [Debug] [ComfyUI-0/STDERR] 
2024-07-21 16:55:58.286 [Debug] [ComfyUI-0/STDERR] Starting server
2024-07-21 16:55:58.286 [Debug] [ComfyUI-0/STDERR] 
2024-07-21 16:55:58.286 [Debug] [ComfyUI-0/STDERR] To see the GUI go to: http://127.0.0.1:7821
2024-07-21 16:55:59.788 [Debug] Comfy backend 0 using model folder format: backslash \ due to model SDXL\4thTailism.safetensors
2024-07-21 16:55:59.790 [Debug] ComfyUI-0 self-start port 7821 loop ending (should now be alive)
2024-07-21 16:55:59.902 [Debug] Comfy backend 0 using model folder format: backslash \ due to model SDXL\4thTailism.safetensors
2024-07-21 16:56:00.039 [Debug] Data refreshed!
2024-07-21 16:56:24.989 [Debug] ComfyUI redirection gave non-200 code: '404' for URL: GET 'userdata/workflows%2F.index.json'
2024-07-21 16:56:25.093 [Debug] [ComfyUI-0/STDOUT] FETCH DATA from: F:\ai_stuff\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
2024-07-21 16:56:25.122 [Debug] Comfy backend direct websocket request to ws, have 1 backends available
2024-07-21 16:56:25.124 [Debug] Comfy backend direct offset for new user is 0
2024-07-21 16:56:25.213 [Debug] ComfyUI redirection gave non-200 code: '404' for URL: GET 'userdata/workflows%2F.index.json'
2024-07-21 16:56:29.370 [Debug] [BackendHandler] Backend request #1 for model SDXL/autismmixSDXL_autismmixConfetti.safetensors, maxWait=7.00:00:00.
2024-07-21 16:56:29.373 [Debug] [BackendHandler] backend #0 will load a model: SDXL/autismmixSDXL_autismmixConfetti.safetensors, with 1 requests waiting for 0 seconds
2024-07-21 16:56:31.462 [Debug] [ComfyUI-0/STDERR] got prompt
2024-07-21 16:56:31.860 [Debug] [ComfyUI-0/STDERR] model_type EPS
2024-07-21 16:56:33.228 [Debug] [ComfyUI-0/STDERR] Using pytorch attention in VAE
2024-07-21 16:56:33.229 [Debug] [ComfyUI-0/STDERR] Using pytorch attention in VAE
2024-07-21 16:56:34.098 [Debug] [ComfyUI-0/STDERR] loaded straight to GPU
2024-07-21 16:56:34.098 [Debug] [ComfyUI-0/STDERR] Requested to load SDXL
2024-07-21 16:56:34.098 [Debug] [ComfyUI-0/STDERR] Loading 1 new model
2024-07-21 16:56:34.626 [Debug] [ComfyUI-0/STDERR] Requested to load AutoencoderKL
2024-07-21 16:56:34.626 [Debug] [ComfyUI-0/STDERR] Loading 1 new model
2024-07-21 16:56:34.816 [Debug] [ComfyUI-0/STDERR] F:\ai_stuff\SwarmUI\dlbackend\comfy\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py:235: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
2024-07-21 16:56:34.816 [Debug] [ComfyUI-0/STDERR]   out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0.0, is_causal=False)
2024-07-21 16:56:34.948 [Debug] [ComfyUI-0/STDERR] Prompt executed in 3.48 seconds
2024-07-21 16:56:35.048 [Debug] [BackendHandler] backend #0 loaded model, returning to pool
2024-07-21 16:56:35.436 [Debug] [BackendHandler] Backend request #1 found correct model on #0
2024-07-21 16:56:35.436 [Debug] [BackendHandler] Backend request #1 finished.
2024-07-21 16:56:35.448 [Debug] Refused to generate image for local: Something went wrong while generating images.
```

### Other

the exact error message it produces is the below
```
2024-07-21 16:56:35.448 [Error] Internal error processing T2I request: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at SwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.<>c__DisplayClass22_0.<CreateWorkflow>g__getLoras|5() in F:\ai_stuff\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 613
   at SwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.<>c__DisplayClass22_0.<CreateWorkflow>b__2(String tag) in F:\ai_stuff\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 638
   at FreneticUtilities.FreneticToolkit.StringConversionHelper.QuickSimpleTagFiller(String taggedText, String prefix, String suffix, Func`2 tagReader, Boolean doSubtags, Int32 maxRecurse)
   at SwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.CreateWorkflow(T2IParamInput user_input, Func`2 initImageFixer, String ModelFolderFormat, HashSet`1 features) in F:\ai_stuff\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 569
   at SwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput) in F:\ai_stuff\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 726
   at SwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in F:\ai_stuff\SwarmUI\src\Text2Image\T2IEngine.cs:line 264
```
This doesn't happen if I have at least one lora loaded

**Comment by mcmonkey4eva** [comment]
fixed
